{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSections"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/resultlistview\/numberofsections(in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/resultlistview\/numberofsections(in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView\/numberOfSections(in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDataSource.numberOfSections(in:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSections"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"numberOfSections(in:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ProductRecognition@objc(cs)ResultListView(im)numberOfSectionsInTableView:","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"numberOfSectionsInTableView:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView\/UITableViewDataSource-Implementations"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView/UITableViewDataSource-Implementations":{"role":"collectionGroup","title":"UITableViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView\/UITableViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/resultlistview\/uitableviewdatasource-implementations"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView/numberOfSections(in:)":{"role":"symbol","title":"numberOfSections(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSections"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView\/numberOfSections(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfSectionsInTableView:"}],"url":"\/documentation\/productrecognition\/resultlistview\/numberofsections(in:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView":{"role":"symbol","title":"ResultListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"abstract":[{"type":"text","text":"A view that displays a list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListView"}],"url":"\/documentation\/productrecognition\/resultlistview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"numberOfSectionsInTableView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInTableView:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"numberOfSectionsInTableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView~1numberOfSections(in:)\/title","value":"numberOfSectionsInTableView:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView~1numberOfSections(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInTableView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/title","value":"ResultListView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}