{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"feedBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation","text":"CVPixelBufferOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withScoreThreshold"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scoreThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/imageprocessor\/feedbuffer(_:buffer:withrotation:withscorethreshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/imageprocessor\/feedbuffer(_:buffer:withrotation:withscorethreshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor\/feedBuffer(_:buffer:withRotation:withScoreThreshold:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"feedBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withScoreThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"title":"feedBuffer(_:buffer:withRotation:withScoreThreshold:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ImageProcessor(im)feedBuffer:buffer:withRotation:withScoreThreshold:","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"feedBuffer:buffer:withRotation:withScoreThreshold:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageProcessor/feedBuffer(_:buffer:withRotation:withScoreThreshold:)":{"role":"symbol","title":"feedBuffer(_:buffer:withRotation:withScoreThreshold:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"feedBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withScoreThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor\/feedBuffer(_:buffer:withRotation:withScoreThreshold:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"feedBuffer:buffer:withRotation:withScoreThreshold:"}],"url":"\/documentation\/productrecognition\/imageprocessor\/feedbuffer(_:buffer:withrotation:withscorethreshold:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CVPixelBufferOrientation":{"role":"symbol","title":"CVPixelBufferOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPixelBufferOrientation"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientation"}],"url":"\/documentation\/productrecognition\/cvpixelbufferorientation"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageProcessor":{"role":"symbol","title":"ImageProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageProcessor"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageProcessor"}],"url":"\/documentation\/productrecognition\/imageprocessor"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"feedBuffer:buffer:withRotation:withScoreThreshold:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"feedBuffer:buffer:withRotation:withScoreThreshold:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"feedBuffer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"imageUid"},{"kind":"text","text":" "},{"kind":"identifier","text":"buffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__CVBuffer","preciseIdentifier":"c:@S@__CVBuffer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"withRotation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation","text":"CVPixelBufferOrientation"},{"kind":"text","text":")"},{"kind":"internalParam","text":"rotation"},{"kind":"text","text":" "},{"kind":"identifier","text":"withScoreThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":")"},{"kind":"internalParam","text":"scoreThreshold"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor~1feedBuffer(_:buffer:withRotation:withScoreThreshold:)\/title","value":"feedBuffer:buffer:withRotation:withScoreThreshold:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor~1feedBuffer(_:buffer:withRotation:withScoreThreshold:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"feedBuffer:buffer:withRotation:withScoreThreshold:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1CVPixelBufferOrientation\/title","value":"CVPixelBufferOrientation"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1CVPixelBufferOrientation\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor\/title","value":"ImageProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor\/fragments","value":[{"kind":"identifier","text":"ImageProcessor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}