{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLatestItemsTrackingData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/TrackedDataObjC","preciseIdentifier":"c:objc(cs)TrackedDataObjC","text":"TrackedDataObjC"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/imageprocessor\/getlatestitemstrackingdata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/imageprocessor\/getlatestitemstrackingdata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor\/getLatestItemsTrackingData()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLatestItemsTrackingData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TrackedDataObjC","preciseIdentifier":"c:objc(cs)TrackedDataObjC"}],"title":"getLatestItemsTrackingData()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ImageProcessor(im)getLatestItemsTrackingData","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"getLatestItemsTrackingData"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageProcessor/getLatestItemsTrackingData()":{"role":"symbol","title":"getLatestItemsTrackingData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLatestItemsTrackingData"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TrackedDataObjC","preciseIdentifier":"c:objc(cs)TrackedDataObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor\/getLatestItemsTrackingData()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLatestItemsTrackingData"}],"url":"\/documentation\/productrecognition\/imageprocessor\/getlatestitemstrackingdata()"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageProcessor":{"role":"symbol","title":"ImageProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageProcessor"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageProcessor"}],"url":"\/documentation\/productrecognition\/imageprocessor"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/TrackedDataObjC":{"role":"symbol","title":"TrackedDataObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackedDataObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/TrackedDataObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TrackedDataObjC"}],"url":"\/documentation\/productrecognition\/trackeddataobjc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getLatestItemsTrackingData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLatestItemsTrackingData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/TrackedDataObjC","preciseIdentifier":"c:objc(cs)TrackedDataObjC","text":"TrackedDataObjC"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getLatestItemsTrackingData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor~1getLatestItemsTrackingData()\/title","value":"getLatestItemsTrackingData"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor~1getLatestItemsTrackingData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLatestItemsTrackingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor\/title","value":"ImageProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor\/fragments","value":[{"kind":"identifier","text":"ImageProcessor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1TrackedDataObjC\/title","value":"TrackedDataObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1TrackedDataObjC\/fragments","value":[{"kind":"identifier","text":"TrackedDataObjC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}