{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUIImageForDetection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"detectionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/imageprocessor\/getuiimagefordetection(withid:forimageuid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/imageprocessor\/getuiimagefordetection(withid:forimageuid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor\/getUIImageForDetection(withId:forImageUid:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUIImageForDetection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"title":"getUIImageForDetection(withId:forImageUid:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ImageProcessor(im)getUIImageForDetectionWithId:forImageUid:","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"getUIImageForDetectionWithId:forImageUid:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageProcessor":{"role":"symbol","title":"ImageProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageProcessor"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageProcessor"}],"url":"\/documentation\/productrecognition\/imageprocessor"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageProcessor/getUIImageForDetection(withId:forImageUid:)":{"role":"symbol","title":"getUIImageForDetection(withId:forImageUid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUIImageForDetection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forImageUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor\/getUIImageForDetection(withId:forImageUid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUIImageForDetectionWithId:forImageUid:"}],"url":"\/documentation\/productrecognition\/imageprocessor\/getuiimagefordetection(withid:forimageuid:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getUIImageForDetectionWithId:forImageUid:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUIImageForDetectionWithId:forImageUid:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getUIImageForDetectionWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"unsigned long","preciseIdentifier":"c:l"},{"kind":"text","text":")"},{"kind":"internalParam","text":"detectionId"},{"kind":"text","text":" "},{"kind":"identifier","text":"forImageUid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"imageUid"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor\/title","value":"ImageProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor\/fragments","value":[{"kind":"identifier","text":"ImageProcessor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor~1getUIImageForDetection(withId:forImageUid:)\/title","value":"getUIImageForDetectionWithId:forImageUid:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor~1getUIImageForDetection(withId:forImageUid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUIImageForDetectionWithId:forImageUid:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}