{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectorVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectorVersionObjC","preciseIdentifier":"c:@E@DetectorVersionObjC","text":"DetectorVersionObjC"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/addproductsviewcontroller\/detectorversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/addproductsviewcontroller\/detectorversion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/AddProductsViewController\/detectorVersion","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectorVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectorVersionObjC","preciseIdentifier":"c:@E@DetectorVersionObjC"}],"title":"detectorVersion","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AddProductsViewController(py)detectorVersion","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"detectorVersion"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/AddProductsViewController"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/DetectorVersionObjC":{"role":"symbol","title":"DetectorVersionObjC","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectorVersionObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectorVersionObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectorVersionObjC"}],"url":"\/documentation\/productrecognition\/detectorversionobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/AddProductsViewController":{"role":"symbol","title":"AddProductsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddProductsViewController"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/AddProductsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddProductsViewController"}],"url":"\/documentation\/productrecognition\/addproductsviewcontroller"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/AddProductsViewController/detectorVersion":{"role":"symbol","title":"detectorVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectorVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectorVersionObjC","preciseIdentifier":"c:@E@DetectorVersionObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/AddProductsViewController\/detectorVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectorVersion"}],"url":"\/documentation\/productrecognition\/addproductsviewcontroller\/detectorversion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"detectorVersion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detectorVersion"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectorVersionObjC","preciseIdentifier":"c:@E@DetectorVersionObjC","text":"DetectorVersionObjC"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectorVersion"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectorVersionObjC\/title","value":"DetectorVersionObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectorVersionObjC\/fragments","value":[{"kind":"identifier","text":"DetectorVersionObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1AddProductsViewController\/title","value":"AddProductsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1AddProductsViewController\/fragments","value":[{"kind":"identifier","text":"AddProductsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1AddProductsViewController~1detectorVersion\/title","value":"detectorVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1AddProductsViewController~1detectorVersion\/fragments","value":[{"kind":"identifier","text":"detectorVersion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}