{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/detectionresultobjc\/uid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/detectionresultobjc\/uid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC\/uid","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"uid","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)DetectionResultObjC(py)uid","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"uid"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/DetectionResultObjC":{"role":"symbol","title":"DetectionResultObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionResultObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectionResultObjC"}],"url":"\/documentation\/productrecognition\/detectionresultobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/DetectionResultObjC/uid":{"role":"symbol","title":"uid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC\/uid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uid"}],"url":"\/documentation\/productrecognition\/detectionresultobjc\/uid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"uid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"uid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"unsigned long","preciseIdentifier":"c:l"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectionResultObjC\/title","value":"DetectionResultObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectionResultObjC\/fragments","value":[{"kind":"identifier","text":"DetectionResultObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectionResultObjC~1uid\/title","value":"uid"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectionResultObjC~1uid\/fragments","value":[{"kind":"identifier","text":"uid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}