{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"V_MOBILE_1_3_0"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/embedderversionobjc\/v_mobile_1_3_0"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/embedderversionobjc\/v_mobile_1_3_0"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/V_MOBILE_1_3_0","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"V_MOBILE_1_3_0"}],"title":"EmbedderVersionObjC.V_MOBILE_1_3_0","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@EmbedderVersionObjC@V_MOBILE_1_3_0","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"V_MOBILE_1_3_0"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/EmbedderVersionObjC/V_MOBILE_1_3_0":{"role":"symbol","title":"EmbedderVersionObjC.V_MOBILE_1_3_0","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"V_MOBILE_1_3_0"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/V_MOBILE_1_3_0","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"V_MOBILE_1_3_0"}],"url":"\/documentation\/productrecognition\/embedderversionobjc\/v_mobile_1_3_0"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/EmbedderVersionObjC":{"role":"symbol","title":"EmbedderVersionObjC","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbedderVersionObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmbedderVersionObjC"}],"url":"\/documentation\/productrecognition\/embedderversionobjc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"V_MOBILE_1_3_0"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"V_MOBILE_1_3_0"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"V_MOBILE_1_3_0"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC~1V_MOBILE_1_3_0\/title","value":"V_MOBILE_1_3_0"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC~1V_MOBILE_1_3_0\/fragments","value":[{"kind":"identifier","text":"V_MOBILE_1_3_0"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC\/title","value":"EmbedderVersionObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC\/fragments","value":[{"kind":"identifier","text":"EmbedderVersionObjC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}