{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC","preciseIdentifier":"c:objc(cs)DetectionResultObjC","text":"DetectionResultObjC"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/processingdata\/detectionresults"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/processingdata\/detectionresults"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProcessingData\/detectionResults","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DetectionResultObjC","preciseIdentifier":"c:objc(cs)DetectionResultObjC"},{"kind":"text","text":"]"}],"title":"detectionResults","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ProcessingData(py)detectionResults","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"detectionResults"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProcessingData"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProcessingData":{"role":"symbol","title":"ProcessingData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingData"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProcessingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProcessingData"}],"url":"\/documentation\/productrecognition\/processingdata"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProcessingData/detectionResults":{"role":"symbol","title":"detectionResults","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionResults"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DetectionResultObjC","preciseIdentifier":"c:objc(cs)DetectionResultObjC"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProcessingData\/detectionResults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectionResults"}],"url":"\/documentation\/productrecognition\/processingdata\/detectionresults"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/DetectionResultObjC":{"role":"symbol","title":"DetectionResultObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionResultObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectionResultObjC"}],"url":"\/documentation\/productrecognition\/detectionresultobjc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"detectionResults"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detectionResults"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DetectionResultObjC *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detectionResults"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ProcessingData\/title","value":"ProcessingData"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ProcessingData\/fragments","value":[{"kind":"identifier","text":"ProcessingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ProcessingData~1detectionResults\/title","value":"detectionResults"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ProcessingData~1detectionResults\/fragments","value":[{"kind":"identifier","text":"detectionResults"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectionResultObjC\/title","value":"DetectionResultObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectionResultObjC\/fragments","value":[{"kind":"identifier","text":"DetectionResultObjC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}