{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The framework scans the entire screen by default. You can focus on a smaller area instead by setting the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["singlePhotoVC.captureRegion = CGRect(x: 100, y: 100, width: 200, height: 600)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A custom icon can be be used for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton"},{"type":"text","text":"."}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-capture-default"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-capture-custom"}]}]]],"header":"row"},{"type":"codeListing","syntax":"swift","code":["singlePhotoVC.shutterButton.setImage(UIImage(systemName: \"camera.circle.fill\",","                                             withConfiguration: UIImage.SymbolConfiguration(pointSize: 80)),","                                     for: .normal)","singlePhotoVC.shutterButton.imageView?.tintColor = UIColor.green"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/customcaptureview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/customcaptureview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion"},{"type":"text","text":" or replace the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton"},{"type":"text","text":" icon."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Capture View","role":"article","modules":[{"name":"ProductRecognition"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC"]]},"seeAlsoSections":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomScan":{"role":"article","title":"Scan View","abstract":[{"type":"text","text":"Modify the scanning activity indicator and the bottom bar for scanning again."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customscan"},"screenshot-capture-custom":{"alt":"Custom Shutter","type":"image","identifier":"screenshot-capture-custom","variants":[{"url":"\/images\/screenshot-capture-custom.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SubclassSinglePhoto":{"role":"article","title":"Subclassing SinglePhotoVC","abstract":[{"type":"text","text":"If you would like to overlay images or set the area to be captured, try subclassing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/subclasssinglephoto"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomSinglePhotoVC":{"role":"collectionGroup","title":"Customizing SinglePhotoVC","abstract":[{"type":"text","text":"Design the interface to better suit your app."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customsinglephotovc"},"screenshot-capture-default":{"alt":"Default Shutter","type":"image","identifier":"screenshot-capture-default","variants":[{"url":"\/images\/screenshot-capture-default.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/captureRegion":{"role":"symbol","title":"captureRegion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureRegion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The region of the camera preview to be captured."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/captureregion"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"A view controller that manages the interface for capturing a single photo to be used for product detection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/productrecognition\/singlephotovc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/shutterButton":{"role":"symbol","title":"shutterButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"A button for capturing an image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/shutterbutton"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomResults":{"role":"article","title":"Results View","abstract":[{"type":"text","text":"Customize result banners and cards."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customresults"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}