{"seeAlsoSections":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Most elements in the view are customizable. You can also subclass SinglePhotoVC to add layers to the view."}]}]}],"variants":[{"paths":["\/documentation\/productrecognition\/customsinglephotovc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/customsinglephotovc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Design the interface to better suit your app."}],"kind":"article","metadata":{"modules":[{"name":"ProductRecognition"}],"role":"collectionGroup","title":"Customizing SinglePhotoVC"},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"]]},"topicSections":[{"title":"Customizable Elements","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults"]},{"title":"Creating a Custom Camera View","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"]}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/captureRegion":{"role":"symbol","title":"captureRegion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureRegion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The region of the camera preview to be captured."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/captureregion"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomCaptureView":{"role":"article","title":"Capture View","abstract":[{"type":"text","text":"Set a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion"},{"type":"text","text":" or replace the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton"},{"type":"text","text":" icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customcaptureview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/shutterButton":{"role":"symbol","title":"shutterButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"A button for capturing an image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/shutterbutton"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"A view controller that manages the interface for capturing a single photo to be used for product detection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/productrecognition\/singlephotovc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SubclassSinglePhoto":{"role":"article","title":"Subclassing SinglePhotoVC","abstract":[{"type":"text","text":"If you would like to overlay images or set the area to be captured, try subclassing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/subclasssinglephoto"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomResults":{"role":"article","title":"Results View","abstract":[{"type":"text","text":"Customize result banners and cards."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customresults"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomScan":{"role":"article","title":"Scan View","abstract":[{"type":"text","text":"Modify the scanning activity indicator and the bottom bar for scanning again."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customscan"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Customizable Elements","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults"]},{"title":"Creating a Custom Camera View","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}