{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once products are recognized by the SDK, a summary of results is displayed below the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainButton"},{"type":"text","text":". Tapping on the summary will show the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView"},{"type":"text","text":" containing the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell"},{"type":"text","text":"."}]},{"style":"tip","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can customize the summary view via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainConfiguration"},{"type":"text","text":"."}]}],"type":"aside","name":"Tip"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each detected product will have a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator"},{"type":"text","text":" and tapping on the indicator will expand to show a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner"},{"type":"text","text":". Tapping on the banner will show "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC"}]},{"anchor":"Samples","level":2,"type":"heading","text":"Samples"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator"},{"type":"text","text":" via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicatorConfiguration"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["ResultIndicatorConfiguration.shared.contentBackgroundColor = .blue","ResultIndicatorConfiguration.shared.selectedProductBackgroundColor = .blue","ResultIndicatorConfiguration.shared.productIcon = UIImage(systemName: \"bag.circle\")","ResultIndicatorConfiguration.shared.selectedProductIcon = UIImage(systemName: \"bag.circle.fill\")","ResultIndicatorConfiguration.shared.promotionIcon = UIImage(systemName: \"tag.circle\")","ResultIndicatorConfiguration.shared.selectedPromotionIcon = UIImage(systemName: \"tag.circle.fill\")","ResultIndicatorConfiguration.shared.iconTintColor = .yellow","ResultIndicatorConfiguration.shared.selectedIconTintColor = .orange","ResultIndicatorConfiguration.shared.pulseAnimationDuration = 0.5","ResultIndicatorConfiguration.shared.pulseTintColor = .systemPink","ResultIndicatorConfiguration.shared.resizeAnimationDuration = 0.1","ResultIndicatorConfiguration.shared.badgeBackgroundColor = .red","ResultIndicatorConfiguration.shared.badgeFont = UIFont.boldSystemFont(ofSize: 12)","ResultIndicatorConfiguration.shared.badgeTextColor = .green","ResultIndicatorConfiguration.shared.badgeSize = CGSize(width: 30, height: 30)","ResultIndicatorConfiguration.shared.selectedTextFont = UIFont.boldSystemFont(ofSize: 14)","ResultIndicatorConfiguration.shared.selectedTextColor = UIColor.white"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-tags-default"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-tags-custom"}]}]]],"header":"row"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here are customizable objects in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerConfiguration"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["ResultBannerConfiguration.shared.contentBackgroundColor = UIColor.lightGray","ResultBannerConfiguration.shared.highlightedBackgroundColor = UIColor.orange","ResultBannerConfiguration.shared.highlightedFont = UIFont.boldSystemFont(ofSize: 14)","ResultBannerConfiguration.shared.highlightedTextColor = UIColor.blue","ResultBannerConfiguration.shared.photoContentMode = UIView.ContentMode.scaleToFill","ResultBannerConfiguration.shared.titleTextColor = UIColor.green","ResultBannerConfiguration.shared.titleFont = UIFont.italicSystemFont(ofSize: 18)","ResultBannerConfiguration.shared.subtitleTextColor = UIColor.green","ResultBannerConfiguration.shared.subtitleFont = UIFont.italicSystemFont(ofSize: 16)","ResultBannerConfiguration.shared.tagImage = UIImage(systemName: \"tag.circle.fill\")","ResultBannerConfiguration.shared.tagBackgroundColor = UIColor.systemPink","ResultBannerConfiguration.shared.tagTintColor = UIColor.green","ResultBannerConfiguration.shared.detailTextColor = UIColor.yellow","ResultBannerConfiguration.shared.detailFont = UIFont.monospacedSystemFont(ofSize: 11, weight: .thin)","ResultBannerConfiguration.shared.scrollViewHorizontalGap = 15","ResultBannerConfiguration.shared.scrollViewHorizontalInset = 15"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-banner-default"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-banner-custom"}]}]]],"header":"row"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Below is an example of a configuration for the view containing the list of results using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListConfiguration"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["ResultListConfiguration.shared.cardBackgroundColor = UIColor.darkGray","ResultListConfiguration.shared.cardHandleBarColor = UIColor.white","ResultListConfiguration.shared.summaryTextColor = UIColor.green","ResultListConfiguration.shared.summaryFont = UIFont.monospacedSystemFont(ofSize: 16, weight: .bold)","ResultListConfiguration.shared.headerHeight = 15","ResultListConfiguration.shared.headerFont = UIFont.boldSystemFont(ofSize: 16)","ResultListConfiguration.shared.headerTextColor = UIColor.brown","ResultListConfiguration.shared.headerPromotionsText = \"Promotions\"","ResultListConfiguration.shared.headerProductsText = \"Products Only\""]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result cards are also customizable using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCellConfiguration"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["ResultListCellConfiguration.shared.contentBackgroundColor = UIColor.gray","ResultListCellConfiguration.shared.borderCornerRadius = 10","ResultListCellConfiguration.shared.borderColor = UIColor.blue","ResultListCellConfiguration.shared.borderWidth = 5","ResultListCellConfiguration.shared.promotionBorderColor = UIColor.red","ResultListCellConfiguration.shared.highlightedBackgroundColor = UIColor.orange","ResultListCellConfiguration.shared.highlightedFont = UIFont.boldSystemFont(ofSize: 14)","ResultListCellConfiguration.shared.highlightedTextColor = UIColor.blue","ResultListCellConfiguration.shared.photoContentMode = UIView.ContentMode.scaleAspectFill","ResultListCellConfiguration.shared.tagImage = UIImage(systemName: \"tag.circle.fill\")","ResultListCellConfiguration.shared.tagBackgroundColor = UIColor.systemPink","ResultListCellConfiguration.shared.tagTintColor = UIColor.green","ResultListCellConfiguration.shared.titleTextColor = UIColor.green","ResultListCellConfiguration.shared.titleFont = UIFont.italicSystemFont(ofSize: 18)","ResultListCellConfiguration.shared.subtitleFont = UIFont.boldSystemFont(ofSize: 16)","ResultListCellConfiguration.shared.subtitleTextColor = UIColor.green","ResultListCellConfiguration.shared.detailFont = UIFont.monospacedSystemFont(ofSize: 12, weight: .thin)","ResultListCellConfiguration.shared.detailTextColor = UIColor.red"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-list-default"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-list-custom"}]}]]],"header":"row"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsConfiguration"},{"type":"text","text":" to customize the view with the result details:"}]},{"type":"codeListing","syntax":"swift","code":["ResultDetailsConfiguration.shared.cardBackgroundColor = UIColor.black","ResultDetailsConfiguration.shared.detailBorderColor = UIColor.red","ResultDetailsConfiguration.shared.detailHeaderIcon = UIImage(systemName: \"tag.circle\")","ResultDetailsConfiguration.shared.detailHeaderIconTintColor = UIColor.green","ResultDetailsConfiguration.shared.detailHeaderFont = UIFont.monospacedSystemFont(ofSize: 14, weight: .bold)","ResultDetailsConfiguration.shared.detailHeaderText = \"More Details...\"","ResultDetailsConfiguration.shared.detailHeaderTextColor = UIColor.blue","ResultDetailsConfiguration.shared.mainDetailFont = UIFont.monospacedSystemFont(ofSize: 18, weight: .thin)","ResultDetailsConfiguration.shared.mainDetailTextColor = UIColor.orange","ResultDetailsConfiguration.shared.limitationDetailFont = UIFont.monospacedSystemFont(ofSize: 12, weight: .medium)","ResultDetailsConfiguration.shared.limitationDetailTextColor = UIColor.yellow","ResultDetailsConfiguration.shared.dismissButtonImage = UIImage(systemName: \"xmark.circle\")","ResultDetailsConfiguration.shared.dismissButtonSize = CGSize(width: 40, height: 40)","ResultDetailsConfiguration.shared.dismissButtonTintColor = UIColor.purple","ResultDetailsConfiguration.shared.highlightedBackgroundColor = UIColor.orange","ResultDetailsConfiguration.shared.highlightedFont = UIFont.boldSystemFont(ofSize: 14)","ResultDetailsConfiguration.shared.highlightedTextColor = UIColor.blue","ResultDetailsConfiguration.shared.photoContentMode = UIView.ContentMode.scaleAspectFill","ResultDetailsConfiguration.shared.tagImage = UIImage(systemName: \"tag.circle.fill\")","ResultDetailsConfiguration.shared.tagBackgroundColor = UIColor.systemPink","ResultDetailsConfiguration.shared.tagTintColor = UIColor.green","ResultDetailsConfiguration.shared.titleTextColor = UIColor.green","ResultDetailsConfiguration.shared.titleFont = UIFont.italicSystemFont(ofSize: 18)"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-details-default"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-details-custom"}]}]]],"header":"row"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/customresults"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/customresults"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Customize result banners and cards."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Results View","role":"article","modules":[{"name":"ProductRecognition"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC"]]},"seeAlsoSections":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsConfiguration":{"role":"symbol","title":"ResultDetailsConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a result details view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsConfiguration"}],"url":"\/documentation\/productrecognition\/resultdetailsconfiguration"},"screenshot-details-default":{"alt":"Details_Default","type":"image","identifier":"screenshot-details-default","variants":[{"url":"\/images\/screenshot-details-default.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/captureRegion":{"role":"symbol","title":"captureRegion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureRegion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The region of the camera preview to be captured."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/captureregion"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"A view controller that manages the interface for capturing a single photo to be used for product detection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/productrecognition\/singlephotovc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/productrecognition\/resultbanner"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC":{"role":"symbol","title":"ResultDetailsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}],"url":"\/documentation\/productrecognition\/resultdetailsvc"},"screenshot-tags-default":{"alt":"Tags_Default","type":"image","identifier":"screenshot-tags-default","variants":[{"url":"\/images\/screenshot-tags-default.png","traits":["1x","light"]}]},"screenshot-tags-custom":{"alt":"Tags_Custom","type":"image","identifier":"screenshot-tags-custom","variants":[{"url":"\/images\/screenshot-tags-custom.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultIndicator":{"role":"symbol","title":"ResultIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicator"}],"abstract":[{"type":"text","text":"A view that indicates a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicator"}],"url":"\/documentation\/productrecognition\/resultindicator"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomSinglePhotoVC":{"role":"collectionGroup","title":"Customizing SinglePhotoVC","abstract":[{"type":"text","text":"Design the interface to better suit your app."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customsinglephotovc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultIndicatorConfiguration":{"role":"symbol","title":"ResultIndicatorConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicatorConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a promotion indicator."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicatorConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicatorConfiguration"}],"url":"\/documentation\/productrecognition\/resultindicatorconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomCaptureView":{"role":"article","title":"Capture View","abstract":[{"type":"text","text":"Set a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion"},{"type":"text","text":" or replace the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton"},{"type":"text","text":" icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customcaptureview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerConfiguration":{"role":"symbol","title":"ResultBannerConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a promotion banner."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerConfiguration"}],"url":"\/documentation\/productrecognition\/resultbannerconfiguration"},"screenshot-list-default":{"alt":"List_Default","type":"image","identifier":"screenshot-list-default","variants":[{"url":"\/images\/screenshot-list-default.png","traits":["1x","light"]}]},"screenshot-banner-custom":{"alt":"Banner_Custom","type":"image","identifier":"screenshot-banner-custom","variants":[{"url":"\/images\/screenshot-banner-custom.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell":{"role":"symbol","title":"ResultListCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"}],"abstract":[{"type":"text","text":"A table view cell that displays information on the list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCell"}],"url":"\/documentation\/productrecognition\/resultlistcell"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCellConfiguration":{"role":"symbol","title":"ResultListCellConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCellConfiguration"}],"abstract":[{"type":"text","text":"The configuration that describes a result list row cell."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCellConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCellConfiguration"}],"url":"\/documentation\/productrecognition\/resultlistcellconfiguration"},"screenshot-list-custom":{"alt":"List_Custom","type":"image","identifier":"screenshot-list-custom","variants":[{"url":"\/images\/screenshot-list-custom.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView":{"role":"symbol","title":"ResultListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"abstract":[{"type":"text","text":"A view that displays a list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListView"}],"url":"\/documentation\/productrecognition\/resultlistview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomScan":{"role":"article","title":"Scan View","abstract":[{"type":"text","text":"Modify the scanning activity indicator and the bottom bar for scanning again."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customscan"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/shutterButton":{"role":"symbol","title":"shutterButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"A button for capturing an image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/shutterbutton"},"screenshot-details-custom":{"alt":"Details_Custom","type":"image","identifier":"screenshot-details-custom","variants":[{"url":"\/images\/screenshot-details-custom.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanAgainConfiguration":{"role":"symbol","title":"ScanAgainConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanAgainConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes the scan again button and container."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanAgainConfiguration"}],"url":"\/documentation\/productrecognition\/scanagainconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SubclassSinglePhoto":{"role":"article","title":"Subclassing SinglePhotoVC","abstract":[{"type":"text","text":"If you would like to overlay images or set the area to be captured, try subclassing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/subclasssinglephoto"},"screenshot-banner-default":{"alt":"Banner_Default","type":"image","identifier":"screenshot-banner-default","variants":[{"url":"\/images\/screenshot-banner-default.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanAgainButton":{"role":"symbol","title":"ScanAgainButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanAgainButton"}],"abstract":[{"type":"text","text":"A specialized button for placement on a result view controller."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanAgainButton"}],"url":"\/documentation\/productrecognition\/scanagainbutton"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListConfiguration":{"role":"symbol","title":"ResultListConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a promotion list."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListConfiguration"}],"url":"\/documentation\/productrecognition\/resultlistconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/title","value":"ResultIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/fragments","value":[{"kind":"identifier","text":"ResultIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/title","value":"ResultListCell"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/fragments","value":[{"kind":"identifier","text":"ResultListCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/title","value":"ResultListView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanAgainButton\/title","value":"ScanAgainButton"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanAgainButton\/fragments","value":[{"kind":"identifier","text":"ScanAgainButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}