{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An indicator is showed on screen to signify that scanning is in progress. After a scanning session, a navigation bar is shown at the bottom of the screen to allow the user to scan again."}]},{"anchor":"Samples","level":2,"type":"heading","text":"Samples"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Below is a sample code for modifying the text and colors of the indicator through "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityConfiguration"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["ScanActivityConfiguration.shared.scanningText = \"Scanning image. Please wait for a moment...\"","ScanActivityConfiguration.shared.noResultText = \"No Result Text\"","ScanActivityConfiguration.shared.resultText = \"Result Text\"","ScanActivityConfiguration.shared.contentBackgroundColor = UIColor.purple","ScanActivityConfiguration.shared.font = UIFont.italicSystemFont(ofSize: 20)","ScanActivityConfiguration.shared.textColor = UIColor.orange"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-scanning-default"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-scanning-custom"}]}]]],"header":"row"},{"type":"paragraph","inlineContent":[{"type":"text","text":"And here are the customizable elements is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainConfiguration"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["ScanAgainConfiguration.shared.navigationBarColor = UIColor.gray","ScanAgainConfiguration.shared.borderColor = UIColor.red","ScanAgainConfiguration.shared.borderWidth = 5","ScanAgainConfiguration.shared.borderGap = 2","ScanAgainConfiguration.shared.contentBackgroundColor = UIColor.orange","ScanAgainConfiguration.shared.hideBorder = false","ScanAgainConfiguration.shared.iconImage = UIImage(systemName: \"viewfinder.circle\")","ScanAgainConfiguration.shared.iconTintColor = UIColor.yellow","ScanAgainConfiguration.shared.text = \"Try Scanning Again\"","ScanAgainConfiguration.shared.textFont = UIFont.monospacedSystemFont(ofSize: 16, weight: .bold)","ScanAgainConfiguration.shared.textColor = UIColor.green"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Custom"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-scan-again-default"}]}],[{"type":"paragraph","inlineContent":[{"type":"image","identifier":"screenshot-scan-again-custom"}]}]]],"header":"row"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/customscan"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/customscan"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Modify the scanning activity indicator and the bottom bar for scanning again."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Scan View","role":"article","modules":[{"name":"ProductRecognition"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC"]]},"seeAlsoSections":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"A view controller that manages the interface for capturing a single photo to be used for product detection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/productrecognition\/singlephotovc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/shutterButton":{"role":"symbol","title":"shutterButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"A button for capturing an image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/shutterbutton"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanAgainConfiguration":{"role":"symbol","title":"ScanAgainConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanAgainConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes the scan again button and container."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanAgainConfiguration"}],"url":"\/documentation\/productrecognition\/scanagainconfiguration"},"screenshot-scan-again-custom":{"alt":"Scan_Again_Custom","type":"image","identifier":"screenshot-scan-again-custom","variants":[{"url":"\/images\/screenshot-scan-again-custom.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SubclassSinglePhoto":{"role":"article","title":"Subclassing SinglePhotoVC","abstract":[{"type":"text","text":"If you would like to overlay images or set the area to be captured, try subclassing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/subclasssinglephoto"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/captureRegion":{"role":"symbol","title":"captureRegion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureRegion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The region of the camera preview to be captured."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/captureregion"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomCaptureView":{"role":"article","title":"Capture View","abstract":[{"type":"text","text":"Set a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion"},{"type":"text","text":" or replace the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton"},{"type":"text","text":" icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customcaptureview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomResults":{"role":"article","title":"Results View","abstract":[{"type":"text","text":"Customize result banners and cards."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customresults"},"screenshot-scanning-default":{"alt":"Scanning_Default","type":"image","identifier":"screenshot-scanning-default","variants":[{"url":"\/images\/screenshot-scanning-default.png","traits":["1x","light"]}]},"screenshot-scanning-custom":{"alt":"Scanning_Custom","type":"image","identifier":"screenshot-scanning-custom","variants":[{"url":"\/images\/screenshot-scanning-custom.png","traits":["1x","light"]}]},"screenshot-scan-again-default":{"alt":"Scan_Again_Default","type":"image","identifier":"screenshot-scan-again-default","variants":[{"url":"\/images\/screenshot-scan-again-default.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityConfiguration":{"role":"symbol","title":"ScanActivityConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanActivityConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes the object displayed while scanning."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanActivityConfiguration"}],"url":"\/documentation\/productrecognition\/scanactivityconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomSinglePhotoVC":{"role":"collectionGroup","title":"Customizing SinglePhotoVC","abstract":[{"type":"text","text":"Design the interface to better suit your app."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customsinglephotovc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}