{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbedderVersionObjC"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/embedderversionobjc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/embedderversionobjc"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH","doc:\/\/com.microblink.ProductRecognition\/SY","doc:\/\/com.microblink.ProductRecognition\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/V_MOBILE_1_3_0"]},{"title":"Initializers","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/Equatable-Implementations","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbedderVersionObjC"}],"title":"EmbedderVersionObjC","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@EmbedderVersionObjC","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"EmbedderVersionObjC"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"]]},"references":{"doc://com.microblink.ProductRecognition/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SY"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/EmbedderVersionObjC":{"role":"symbol","title":"EmbedderVersionObjC","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbedderVersionObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmbedderVersionObjC"}],"url":"\/documentation\/productrecognition\/embedderversionobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/EmbedderVersionObjC/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/embedderversionobjc\/rawrepresentable-implementations"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/EmbedderVersionObjC/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/embedderversionobjc\/init(rawvalue:)"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.microblink.ProductRecognition\/s8SendableP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/EmbedderVersionObjC/V_MOBILE_1_3_0":{"role":"symbol","title":"EmbedderVersionObjC.V_MOBILE_1_3_0","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"V_MOBILE_1_3_0"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/V_MOBILE_1_3_0","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"V_MOBILE_1_3_0"}],"url":"\/documentation\/productrecognition\/embedderversionobjc\/v_mobile_1_3_0"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/EmbedderVersionObjC/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/embedderversionobjc\/equatable-implementations"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"EmbedderVersionObjC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"EmbedderVersionObjC"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"EmbedderVersionObjC"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC\/V_MOBILE_1_3_0"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbedderVersionObjC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC\/title","value":"EmbedderVersionObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC\/fragments","value":[{"kind":"identifier","text":"EmbedderVersionObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC~1V_MOBILE_1_3_0\/title","value":"V_MOBILE_1_3_0"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC~1V_MOBILE_1_3_0\/fragments","value":[{"kind":"identifier","text":"V_MOBILE_1_3_0"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}