{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Set-Up-License-Key-for-Authentication","level":2,"type":"heading","text":"Set Up License Key for Authentication"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the license key associated with your app’s bundle identifier."}]}],"type":"aside","name":"Important"},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication, didFinishLaunchingWithOptions","                 launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","","    SDKManager.setLicenseKey(licenseKey: <license key string>)","  ","  return true","}"]},{"anchor":"Add-Camera-Usage-Description","level":2,"type":"heading","text":"Add Camera Usage Description"},{"type":"paragraph","inlineContent":[{"type":"text","text":"iOS requires that you provide a usage description in order to access the camera."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On your app’s Info.plist, add:"}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Key"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Privacy - Camera Usage Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Camera access is needed to capture images of products"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Privacy - Photo Library Additions Usage Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Allow access to save your photo"}]}]]],"header":"row"},{"anchor":"Add-Location-Access-Description","level":2,"type":"heading","text":"Add Location Access Description"},{"type":"paragraph","inlineContent":[{"type":"text","text":"User location is required to enable ProductRecognition’s Store Detection feature. iOS requires that you provide a usage description in order to access the user’s location."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On your app’s Info.plist, add:"}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Key"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Privacy - Location When In Use Usage Description"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"The app uses your location to detect the current store"}]}]]],"header":"row"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/gettingstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GettingStarted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Add the necessary keys to get your project started."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Getting Started","role":"article","modules":[{"name":"ProductRecognition"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"]]},"seeAlsoSections":[{"title":"Setup","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Installation","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SDKManager"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SDKManager":{"role":"symbol","title":"SDKManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKManager"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SDKManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKManager"}],"url":"\/documentation\/productrecognition\/sdkmanager"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Installation":{"role":"article","title":"Installing ProductRecognition","abstract":[{"type":"text","text":"ProductRecognition can be installed via CocoaPods, Carthage, or Swift Package Manager. You can also manually add the framework to your project."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Installation","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/installation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Setup","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Installation"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}