{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Minimum-Requirements","level":2,"type":"heading","text":"Minimum Requirements"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The ProductRecognition framework can be deployed in "},{"type":"strong","inlineContent":[{"type":"text","text":"iOS 13.0 or later"}]},{"type":"text","text":"."}]},{"anchor":"CocoaPods","level":2,"type":"heading","text":"CocoaPods"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/cocoapods.org"},{"type":"text","text":" is a dependency manager for Swift and Objective-C projects. For usage and installation instructions, visit their website."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is a sample barebones "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":" which imports the "},{"type":"codeVoice","code":"ProductRecognition"},{"type":"text","text":" pod:"}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You must include "},{"type":"codeVoice","code":"https:\/\/github.com\/BlinkReceipt\/PodSpecRepo.git"},{"type":"text","text":" as source as the BlinkReceipt pod is hosted in a private spec repository."}]}],"type":"aside","name":"Important"},{"type":"codeListing","syntax":"shell","code":["source 'https:\/\/github.com\/BlinkReceipt\/PodSpecRepo.git'","source 'https:\/\/cdn.cocoapods.org\/'","","platform :ios, '13.0'","","target 'YourTarget' do","    use_frameworks!","","    pod 'ProductRecognition'","end"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After editing your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":", run "},{"type":"codeVoice","code":"pod install"},{"type":"text","text":" and then open the generated "},{"type":"codeVoice","code":".xcworkspace"},{"type":"text","text":" file instead of "},{"type":"codeVoice","code":".xcodeproj"},{"type":"text","text":"."}]},{"anchor":"Carthage","level":2,"type":"heading","text":"Carthage"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/Carthage\/Carthage"},{"type":"text","text":" is a decentralized dependency manager that builds your dependencies and provides you with binary frameworks, but you retain full control over your project structure and setup. Carthage does not automatically modify your project files or your build settings."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To integrate the Product Recognition SDK into your Xcode project using Carthage, specify it in your "},{"type":"codeVoice","code":"Cartfile"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"shell","code":["binary \"https:\/\/raw.githubusercontent.com\/BlinkReceipt\/product-recognition-sdk-ios\/main\/ProductRecognition.json\" ~> 1.0"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After editing your "},{"type":"codeVoice","code":"Cartfile"},{"type":"text","text":", run "},{"type":"codeVoice","code":"carthage update --use-xcframeworks"},{"type":"text","text":" and then add "},{"type":"codeVoice","code":"ProductRecognition.xcframework"},{"type":"text","text":" to your project. It should be located at "},{"type":"codeVoice","code":"~\/Carthage\/Build\/"},{"type":"text","text":"."}]},{"anchor":"Swift-Package-Manager","level":2,"type":"heading","text":"Swift Package Manager"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.swift.org\/package-manager\/"},{"type":"text","text":" is a tool for managing the distribution of Swift code. It’s integrated with the Swift build system to automate the process of downloading, compiling, and linking dependencies."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Xcode, navigate to "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"File > Add Packages"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Go to "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Search or Enter Package URL"}]}]},{"type":"text","text":" at the top-right search bar of the window that appears, then type:"}]},{"type":"codeListing","syntax":"http","code":["https:\/\/github.com\/BlinkReceipt\/product-recognition-sdk-ios.git"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Select "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Up to Next Major Version"}]}]},{"type":"text","text":" on the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“Dependency Rule”"}]}]},{"type":"text","text":" and type "},{"type":"codeVoice","code":"1.0.0"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Click "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Add Package"}]}]}]},{"anchor":"Manual-Installation","level":2,"type":"heading","text":"Manual Installation"},{"anchor":"Embedded-Framework","level":3,"type":"heading","text":"Embedded Framework"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you prefer not to use any dependency managers, you can integrate the Product Recognition SDK into your project manually."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you haven’t initialized your project as a git repository, open "},{"type":"strong","inlineContent":[{"type":"text","text":"Terminal"}]},{"type":"text","text":" and go to the root of your project directory. Run this command:"}]},{"type":"codeListing","syntax":"shell","code":["$ git init"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Add ProductRecognition as a "},{"type":"reference","isActive":true,"identifier":"https:\/\/git-scm.com\/docs\/git-submodule"},{"type":"text","text":" by running the command:"}]},{"type":"codeListing","syntax":"shell","code":["$ git submodule add https:\/\/github.com\/BlinkReceipt\/product-recognition-sdk-ios.git"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Open the new "},{"type":"codeVoice","code":"product-recognition-sdk-ios"},{"type":"text","text":" folder and drag the "},{"type":"codeVoice","code":"ProductRecognition.xcframework"},{"type":"text","text":" into the Project Navigator of your application’s Xcode project."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Select the "},{"type":"codeVoice","code":"ProductRecognition.xcframework"},{"type":"text","text":" in the Project Navigator and verify the deployment target matches that of your application target."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Next, select your application project in the Project Navigator (blue project icon) to navigate to the target configuration window and select the application target under the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“Targets”"}]}]},{"type":"text","text":" heading in the sidebar."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the tab bar at the top of that window, open the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“General”"}]}]},{"type":"text","text":" panel and click on the "},{"type":"codeVoice","code":"+"},{"type":"text","text":" button under the "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“Frameworks, Libraries, and Embedded Content”"}]}]},{"type":"text","text":" section."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On the window that shows, search for “ProductRecognition”. Select "},{"type":"codeVoice","code":"ProductRecognition.xcframework"},{"type":"text","text":" from the list then click "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Add"}]}]},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"On the table’s "},{"type":"emphasis","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"“Embed”"}]}]},{"type":"text","text":" column, make sure that "},{"type":"codeVoice","code":"Embed & Sign"},{"type":"text","text":" is selected."}]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Name"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Embed"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"ProductRecognition.xcframework"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Embed & Sign"}]}]]],"header":"row"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/installation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/installation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Installation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"ProductRecognition can be installed via CocoaPods, Carthage, or Swift Package Manager. You can also manually add the framework to your project."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Installing ProductRecognition","role":"article","modules":[{"name":"ProductRecognition"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"]]},"seeAlsoSections":[{"title":"Setup","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GettingStarted","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SDKManager"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SDKManager":{"role":"symbol","title":"SDKManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKManager"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SDKManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKManager"}],"url":"\/documentation\/productrecognition\/sdkmanager"},"https://github.com/Carthage/Carthage":{"title":"Carthage","titleInlineContent":[{"type":"text","text":"Carthage"}],"type":"link","identifier":"https:\/\/github.com\/Carthage\/Carthage","url":"https:\/\/github.com\/Carthage\/Carthage"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/GettingStarted":{"role":"article","title":"Getting Started","abstract":[{"type":"text","text":"Add the necessary keys to get your project started."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/gettingstarted"},"https://cocoapods.org":{"title":"CocoaPods","titleInlineContent":[{"type":"text","text":"CocoaPods"}],"type":"link","identifier":"https:\/\/cocoapods.org","url":"https:\/\/cocoapods.org"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"https://git-scm.com/docs/git-submodule":{"title":"submodule","titleInlineContent":[{"type":"text","text":"submodule"}],"type":"link","identifier":"https:\/\/git-scm.com\/docs\/git-submodule","url":"https:\/\/git-scm.com\/docs\/git-submodule"},"https://www.swift.org/package-manager/":{"title":"Swift Package Manager","titleInlineContent":[{"type":"text","text":"Swift Package Manager"}],"type":"link","identifier":"https:\/\/www.swift.org\/package-manager\/","url":"https:\/\/www.swift.org\/package-manager\/"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Setup","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GettingStarted"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}