{"seeAlsoSections":[{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/productrecognition\/productinfo"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object containing information of a product and available promotion."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductInfo"}],"title":"ProductInfo","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:18ProductRecognition0A4InfoV","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"ProductInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo\/hasPromotion","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo\/order","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo\/productData","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo\/promotions"]}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo":{"role":"symbol","title":"ProductInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductInfo"}],"abstract":[{"type":"text","text":"An object containing information of a product and available promotion."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductInfo"}],"url":"\/documentation\/productrecognition\/productinfo"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC":{"role":"symbol","title":"ResultVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"abstract":[{"type":"text","text":"A view controller that displays the result of the scanned image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultVC"}],"url":"\/documentation\/productrecognition\/resultvc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/productrecognition\/resultbanner"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView":{"role":"symbol","title":"ResultListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"abstract":[{"type":"text","text":"A view that displays a list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListView"}],"url":"\/documentation\/productrecognition\/resultlistview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo/promotions":{"role":"symbol","title":"promotions","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"promotions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Products","preciseIdentifier":"s:18ProductRecognition8ProductsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"StaticDiscovery","preciseIdentifier":"s:18ProductRecognition8ProductsV15StaticDiscoveryV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Response","preciseIdentifier":"s:18ProductRecognition8ProductsV15StaticDiscoveryV8ResponseV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"PromotionDisplay","preciseIdentifier":"s:18ProductRecognition8ProductsV15StaticDiscoveryV8ResponseV16PromotionDisplayV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The promotions available for the product."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo\/promotions","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/productinfo\/promotions"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell":{"role":"symbol","title":"ResultListCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"}],"abstract":[{"type":"text","text":"A table view cell that displays information on the list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCell"}],"url":"\/documentation\/productrecognition\/resultlistcell"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/productrecognition\/resultbannerscrollview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo/hasPromotion":{"role":"symbol","title":"hasPromotion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasPromotion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value that determines if the product has at least one promotion."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo\/hasPromotion","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/productinfo\/haspromotion"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo/productData":{"role":"symbol","title":"productData","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"productData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Products","preciseIdentifier":"s:18ProductRecognition8ProductsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"StaticDiscovery","preciseIdentifier":"s:18ProductRecognition8ProductsV15StaticDiscoveryV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Response","preciseIdentifier":"s:18ProductRecognition8ProductsV15StaticDiscoveryV8ResponseV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Product","preciseIdentifier":"s:18ProductRecognition8ProductsV15StaticDiscoveryV8ResponseV0A0V"}],"abstract":[{"type":"text","text":"The information about the product."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo\/productData","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/productinfo\/productdata"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo/order":{"role":"symbol","title":"order","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"order"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The order of the product in a collection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo\/order","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/productinfo\/order"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultIndicator":{"role":"symbol","title":"ResultIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicator"}],"abstract":[{"type":"text","text":"A view that indicates a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicator"}],"url":"\/documentation\/productrecognition\/resultindicator"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC":{"role":"symbol","title":"ResultDetailsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}],"url":"\/documentation\/productrecognition\/resultdetailsvc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/title","value":"ResultVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/fragments","value":[{"kind":"identifier","text":"ResultVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/title","value":"ResultListView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/title","value":"ResultListCell"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/fragments","value":[{"kind":"identifier","text":"ResultListCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/title","value":"ResultIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/fragments","value":[{"kind":"identifier","text":"ResultIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}