{"seeAlsoSections":[{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"title":"ResultVC","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ProductRecognition@objc(cs)ResultVC","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"ResultVC"}]},"abstract":[{"type":"text","text":"A view controller that displays the result of the scanned image."}],"sections":[],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH","doc:\/\/com.microblink.ProductRecognition\/s8SendableP","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIContentContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIStateRestoring","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/capturedImage","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/currentStore","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/currentStoreLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/detectedProducts","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/resultBannerView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/resultCardView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/scanAgainButton","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/willDismiss"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/loadReceivedIndexedProducts(_:withPromotions:currentStore:shouldPresent:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewDidLayoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewDidLoad()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewWillAppear(_:)"]}],"variants":[{"paths":["\/documentation\/productrecognition\/resultvc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/resultvc"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.microblink.ProductRecognition/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIContentContainer"},"doc://com.microblink.ProductRecognition/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions"},"doc://com.microblink.ProductRecognition/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/capturedImage":{"role":"symbol","title":"capturedImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The image that was scanned."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/capturedImage","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/capturedimage"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/resultCardView":{"role":"symbol","title":"resultCardView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultCardView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResultListView","preciseIdentifier":"c:@M@ProductRecognition@objc(cs)ResultListView"}],"abstract":[{"type":"text","text":"The view that displays the list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/resultCardView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/resultcardview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/productrecognition\/resultvc\/initwithcoder:"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Store":{"role":"symbol","title":"Store","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Store"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Store","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Store"}],"url":"\/documentation\/productrecognition\/store"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultIndicator":{"role":"symbol","title":"ResultIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicator"}],"abstract":[{"type":"text","text":"A view that indicates a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicator"}],"url":"\/documentation\/productrecognition\/resultindicator"},"doc://com.microblink.ProductRecognition/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment"},"doc://com.microblink.ProductRecognition/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/productrecognition\/resultvc\/viewwillappear(_:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/currentStoreLabel":{"role":"symbol","title":"currentStoreLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentStoreLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScanAgainStoreView","preciseIdentifier":"c:@M@ProductRecognition@objc(cs)ScanAgainStoreView"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/currentStoreLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/currentstorelabel"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/productrecognition\/resultvc\/viewdidload()"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/currentStore":{"role":"symbol","title":"currentStore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentStore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Store","preciseIdentifier":"s:18ProductRecognition5StoreV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Store"},{"type":"text","text":" where the user is, if set."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/currentStore","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/currentstore"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView":{"role":"symbol","title":"ResultListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"abstract":[{"type":"text","text":"A view that displays a list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListView"}],"url":"\/documentation\/productrecognition\/resultlistview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC":{"role":"symbol","title":"ResultVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"abstract":[{"type":"text","text":"A view controller that displays the result of the scanned image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultVC"}],"url":"\/documentation\/productrecognition\/resultvc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/productrecognition\/resultbannerscrollview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/detectedProducts":{"role":"symbol","title":"detectedProducts","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedProducts"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ProductInfo","preciseIdentifier":"s:18ProductRecognition0A4InfoV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"An array of the detected products."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/detectedProducts","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/detectedproducts"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/scanAgainButton":{"role":"symbol","title":"scanAgainButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanAgainButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ScanAgainButton","preciseIdentifier":"c:@M@ProductRecognition@objc(cs)ScanAgainButton"}],"abstract":[{"type":"text","text":"The button for dismissing the result view controller."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/scanAgainButton","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/scanagainbutton"},"doc://com.microblink.ProductRecognition/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.microblink.ProductRecognition\/s8SendableP"},"doc://com.microblink.ProductRecognition/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/productrecognition\/resultbanner"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/productrecognition\/resultvc\/initwithnibname:bundle:"},"doc://com.microblink.ProductRecognition/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSExtensionRequestHandling"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC":{"role":"symbol","title":"ResultDetailsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}],"url":"\/documentation\/productrecognition\/resultdetailsvc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/resultBannerView":{"role":"symbol","title":"resultBannerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultBannerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResultBannerScrollView","preciseIdentifier":"c:@M@ProductRecognition@objc(cs)ResultBannerScrollView"}],"abstract":[{"type":"text","text":"The scrollable view that displays multiple result banners."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/resultBannerView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/resultbannerview"},"doc://com.microblink.ProductRecognition/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/productrecognition\/resultvc\/viewdidlayoutsubviews()"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/loadReceivedIndexedProducts(_:withPromotions:currentStore:shouldPresent:)":{"role":"symbol","title":"loadReceivedIndexedProducts(_:withPromotions:currentStore:shouldPresent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadReceivedIndexedProducts"},{"kind":"text","text":"([("},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ProductInfo","preciseIdentifier":"s:18ProductRecognition0A4InfoV"},{"kind":"text","text":")], "},{"kind":"externalParam","text":"withPromotions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentStore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Store","preciseIdentifier":"s:18ProductRecognition5StoreV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shouldPresent"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"shouldPresent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResultVC","preciseIdentifier":"c:@M@ProductRecognition@objc(cs)ResultVC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Loads the received results from the scanned image, before presentation."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/loadReceivedIndexedProducts(_:withPromotions:currentStore:shouldPresent:)","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/loadreceivedindexedproducts(_:withpromotions:currentstore:shouldpresent:)"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo":{"role":"symbol","title":"ProductInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductInfo"}],"abstract":[{"type":"text","text":"An object containing information of a product and available promotion."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductInfo"}],"url":"\/documentation\/productrecognition\/productinfo"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer"},"doc://com.microblink.ProductRecognition/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIStateRestoring"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell":{"role":"symbol","title":"ResultListCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"}],"abstract":[{"type":"text","text":"A table view cell that displays information on the list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCell"}],"url":"\/documentation\/productrecognition\/resultlistcell"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC/willDismiss":{"role":"symbol","title":"willDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismiss"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"A block to be executed before the view controller is dismissed."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/willDismiss","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultvc\/willdismiss"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ResultVC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ResultVC"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ResultVC"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/initWithCoder:","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/initWithNibName:bundle:","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewDidLayoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewDidLoad()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/title","value":"ResultIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/fragments","value":[{"kind":"identifier","text":"ResultIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/title","value":"ResultListView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/title","value":"ResultVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/fragments","value":[{"kind":"identifier","text":"ResultVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/title","value":"ResultListCell"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/fragments","value":[{"kind":"identifier","text":"ResultListCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}