{"seeAlsoSections":[{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"title":"ResultDetailsVC","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ProductRecognition@objc(cs)ResultDetailsVC","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}]},"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"sections":[],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH","doc:\/\/com.microblink.ProductRecognition\/s8SendableP","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIContentContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIStateRestoring","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/cardView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailHeaderIconView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailHeaderLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailHeaderView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/didDismiss","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/dismissButton","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/highlightedLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/highlightedView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/photoView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/promo","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/scrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/tagImageView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/tagView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/loadPromoDetails(of:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/viewDidLayoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/viewDidLoad()"]}],"variants":[{"paths":["\/documentation\/productrecognition\/resultdetailsvc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/resultdetailsvc"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Customizable via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsConfiguration"},{"type":"text","text":"."}]}]}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/highlightedView":{"role":"symbol","title":"highlightedView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that is highlighted at the top of the view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/highlightedView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/highlightedview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/promo":{"role":"symbol","title":"promo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"promo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Promo","preciseIdentifier":"s:18ProductRecognition5PromoV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The information of the promotion to display"}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/promo","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/promo"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/detailHeaderLabel":{"role":"symbol","title":"detailHeaderLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailHeaderLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label of the text on the detail header."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailHeaderLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/detailheaderlabel"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/detailView":{"role":"symbol","title":"detailView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the detail label."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/detailview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/detailHeaderIconView":{"role":"symbol","title":"detailHeaderIconView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailHeaderIconView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view of the icon on the detail header."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailHeaderIconView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/detailheadericonview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/productrecognition\/resultdetailsvc\/initwithcoder:"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/cardView":{"role":"symbol","title":"cardView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the result details."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/cardView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/cardview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/productrecognition\/resultdetailsvc\/viewdidlayoutsubviews()"},"doc://com.microblink.ProductRecognition/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIContentContainer"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.microblink.ProductRecognition\/s8SendableP"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIStateRestoring"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/productrecognition\/resultdetailsvc\/initwithnibname:bundle:"},"doc://com.microblink.ProductRecognition/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.microblink.ProductRecognition/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.microblink.ProductRecognition/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsConfiguration":{"role":"symbol","title":"ResultDetailsConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a result details view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsConfiguration"}],"url":"\/documentation\/productrecognition\/resultdetailsconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/dismissButton":{"role":"symbol","title":"dismissButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"The button that dismisses the view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/dismissButton","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/dismissbutton"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/didDismiss":{"role":"symbol","title":"didDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The block to be executed when the view is dismissed."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/didDismiss","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/diddismiss"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/productrecognition\/resultbannerscrollview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the primary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/titleLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/titlelabel"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView":{"role":"symbol","title":"ResultListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"abstract":[{"type":"text","text":"A view that displays a list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListView"}],"url":"\/documentation\/productrecognition\/resultlistview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultIndicator":{"role":"symbol","title":"ResultIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicator"}],"abstract":[{"type":"text","text":"A view that indicates a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicator"}],"url":"\/documentation\/productrecognition\/resultindicator"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/tagView":{"role":"symbol","title":"tagView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the tag image view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/tagView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/tagview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/productrecognition\/resultbanner"},"doc://com.microblink.ProductRecognition/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC":{"role":"symbol","title":"ResultDetailsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}],"url":"\/documentation\/productrecognition\/resultdetailsvc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo":{"role":"symbol","title":"ProductInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductInfo"}],"abstract":[{"type":"text","text":"An object containing information of a product and available promotion."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductInfo"}],"url":"\/documentation\/productrecognition\/productinfo"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/detailHeaderView":{"role":"symbol","title":"detailHeaderView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailHeaderView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the detail header."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailHeaderView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/detailheaderview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/highlightedLabel":{"role":"symbol","title":"highlightedLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label of the highlighted view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/highlightedLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/highlightedlabel"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/scrollView":{"role":"symbol","title":"scrollView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"}],"abstract":[{"type":"text","text":"The view that allows the scrolling of its contained result details."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/scrollView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/scrollview"},"doc://com.microblink.ProductRecognition/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"},"doc://com.microblink.ProductRecognition/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell":{"role":"symbol","title":"ResultListCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"}],"abstract":[{"type":"text","text":"A table view cell that displays information on the list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCell"}],"url":"\/documentation\/productrecognition\/resultlistcell"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSExtensionRequestHandling"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC":{"role":"symbol","title":"ResultVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"abstract":[{"type":"text","text":"A view controller that displays the result of the scanned image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultVC"}],"url":"\/documentation\/productrecognition\/resultvc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/detailLabel":{"role":"symbol","title":"detailLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the supplementary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/detailLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/detaillabel"},"doc://com.microblink.ProductRecognition/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/photoView":{"role":"symbol","title":"photoView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that displays the photo of the promotion."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/photoView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/photoview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/loadPromoDetails(of:)":{"role":"symbol","title":"loadPromoDetails(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadPromoDetails"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Promo","preciseIdentifier":"s:18ProductRecognition5PromoV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Loads the promotion details to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/loadPromoDetails(of:)","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/loadpromodetails(of:)"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/productrecognition\/resultdetailsvc\/viewdidload()"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC/tagImageView":{"role":"symbol","title":"tagImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view of the tag icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/tagImageView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultdetailsvc\/tagimageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/initWithCoder:","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/initWithNibName:bundle:","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/viewDidLayoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/title","value":"ResultListView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/title","value":"ResultIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/fragments","value":[{"kind":"identifier","text":"ResultIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/title","value":"ResultListCell"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/fragments","value":[{"kind":"identifier","text":"ResultListCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/title","value":"ResultVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/fragments","value":[{"kind":"identifier","text":"ResultVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}