{"seeAlsoSections":[{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"}],"title":"ResultListCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ProductRecognition@objc(cs)ResultListCell","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"ResultListCell"}]},"abstract":[{"type":"text","text":"A table view cell that displays information on the list of results."}],"sections":[],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/objc(pl)CALayerDelegate","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH","doc:\/\/com.microblink.ProductRecognition\/s8SendableP","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearance","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UICoordinateSpace","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIDynamicItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItemContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UILargeContentViewerItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/init(style:reuseIdentifier:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/contentBackgroundView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/detailLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/highlightedLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/highlightedView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/photoView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/product","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/promo","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/subtitleLabel","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/tagImageView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/tagView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/titleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/layoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/loadProduct(_:withPromotionAtIndex:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/cellHeight"]}],"variants":[{"paths":["\/documentation\/productrecognition\/resultlistcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/resultlistcell"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Customizable via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCellConfiguration"},{"type":"text","text":"."}]}]}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/cellHeight":{"role":"symbol","title":"cellHeight","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The ideal height of the result list cell."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/cellHeight","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/cellheight"},"doc://com.microblink.ProductRecognition/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.microblink.ProductRecognition\/s8SendableP"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/highlightedLabel":{"role":"symbol","title":"highlightedLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label of the highlighted view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/highlightedLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/highlightedlabel"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItemContainer"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo":{"role":"symbol","title":"ProductInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductInfo"}],"abstract":[{"type":"text","text":"An object containing information of a product and available promotion."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductInfo"}],"url":"\/documentation\/productrecognition\/productinfo"},"doc://com.microblink.ProductRecognition/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearance"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/highlightedView":{"role":"symbol","title":"highlightedView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlightedView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that highlights the promotion shown at the top of the result cell."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/highlightedView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/highlightedview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCellConfiguration":{"role":"symbol","title":"ResultListCellConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCellConfiguration"}],"abstract":[{"type":"text","text":"The configuration that describes a result list row cell."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCellConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCellConfiguration"}],"url":"\/documentation\/productrecognition\/resultlistcellconfiguration"},"doc://com.microblink.ProductRecognition/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/productrecognition\/resultbannerscrollview"},"doc://com.microblink.ProductRecognition/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/tagImageView":{"role":"symbol","title":"tagImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view of the tag icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/tagImageView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/tagimageview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC":{"role":"symbol","title":"ResultVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"abstract":[{"type":"text","text":"A view controller that displays the result of the scanned image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultVC"}],"url":"\/documentation\/productrecognition\/resultvc"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusItem"},"doc://com.microblink.ProductRecognition/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)CALayerDelegate"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/init(style:reuseIdentifier:)":{"role":"symbol","title":"init(style:reuseIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CellStyle","preciseIdentifier":"c:@E@UITableViewCellStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/init(style:reuseIdentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/productrecognition\/resultlistcell\/init(style:reuseidentifier:)"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UILargeContentViewerItem"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/product":{"role":"symbol","title":"product","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"product"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProductInfo","preciseIdentifier":"s:18ProductRecognition0A4InfoV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The information of the product to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/product","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/product"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultIndicator":{"role":"symbol","title":"ResultIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicator"}],"abstract":[{"type":"text","text":"A view that indicates a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicator"}],"url":"\/documentation\/productrecognition\/resultindicator"},"doc://com.microblink.ProductRecognition/objc(cs)UITableViewCell":{"type":"unresolvable","title":"UITableViewCell","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)UITableViewCell"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC":{"role":"symbol","title":"ResultDetailsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}],"url":"\/documentation\/productrecognition\/resultdetailsvc"},"doc://com.microblink.ProductRecognition/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UICoordinateSpace"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/detailLabel":{"role":"symbol","title":"detailLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the supplementary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/detailLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/detaillabel"},"doc://com.microblink.ProductRecognition/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAccessibilityIdentification"},"doc://com.microblink.ProductRecognition/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIDynamicItem"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView":{"role":"symbol","title":"ResultListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"abstract":[{"type":"text","text":"A view that displays a list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListView"}],"url":"\/documentation\/productrecognition\/resultlistview"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/tagView":{"role":"symbol","title":"tagView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tagView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view that contains the tag image view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/tagView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/tagview"},"doc://com.microblink.ProductRecognition/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell":{"role":"symbol","title":"ResultListCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"}],"abstract":[{"type":"text","text":"A table view cell that displays information on the list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCell"}],"url":"\/documentation\/productrecognition\/resultlistcell"},"doc://com.microblink.ProductRecognition/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/loadProduct(_:withPromotionAtIndex:)":{"role":"symbol","title":"loadProduct(_:withPromotionAtIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadProduct"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ProductInfo","preciseIdentifier":"s:18ProductRecognition0A4InfoV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPromotionAtIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Loads the information of the product to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/loadProduct(_:withPromotionAtIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/loadproduct(_:withpromotionatindex:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/productrecognition\/resultlistcell\/layoutsubviews()"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/productrecognition\/resultbanner"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/subtitleLabel":{"role":"symbol","title":"subtitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the secondary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/subtitleLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/subtitlelabel"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/photoView":{"role":"symbol","title":"photoView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The photo view of the result list cell."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/photoView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/photoview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/promo":{"role":"symbol","title":"promo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"promo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Promo","preciseIdentifier":"s:18ProductRecognition5PromoV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The information of the promotion to display."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/promo","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/promo"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/contentBackgroundView":{"role":"symbol","title":"contentBackgroundView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentBackgroundView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view of the result list cell that contains the photo and texts."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/contentBackgroundView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/contentbackgroundview"},"doc://com.microblink.ProductRecognition/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions"},"doc://com.microblink.ProductRecognition/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that contains the primary text."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/titleLabel","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultlistcell\/titlelabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ResultListCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ResultListCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ResultListCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/init(style:reuseIdentifier:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UITableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/title","value":"ResultVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/fragments","value":[{"kind":"identifier","text":"ResultVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell~1init(style:reuseIdentifier:)\/title","value":"initWithStyle:reuseIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell~1init(style:reuseIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/title","value":"ResultIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/fragments","value":[{"kind":"identifier","text":"ResultIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/title","value":"ResultListView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/title","value":"ResultListCell"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/fragments","value":[{"kind":"identifier","text":"ResultListCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}