{"seeAlsoSections":[{"title":"Scanning Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainButton"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanActivityViewController"}],"title":"ScanActivityViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ProductRecognition@objc(cs)ScanActivityViewController","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"ScanActivityViewController"}]},"abstract":[{"type":"text","text":"A view controller that you use to display the progress of a scan activity."}],"sections":[],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject","doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP","doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP","doc:\/\/com.microblink.ProductRecognition\/SQ","doc:\/\/com.microblink.ProductRecognition\/SH","doc:\/\/com.microblink.ProductRecognition\/s8SendableP","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIContentContainer","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIStateRestoring","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment","doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/capturedImage","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/imageView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/noResultText","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/resultText","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/scanningAnimationCompletion","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/scanningText"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/showCustomMessage(_:completion:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/showResultMessage(noResult:completion:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/showScanningAnimation(_:)","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/viewDidLayoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/viewDidLoad()"]}],"variants":[{"paths":["\/documentation\/productrecognition\/scanactivityviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/scanactivityviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanActivityViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Customizable via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityConfiguration"},{"type":"text","text":"."}]}]}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/initwithnibname:bundle:"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/scanningText":{"role":"symbol","title":"scanningText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The text displayed when scan is ongoing."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/scanningText","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/scanningtext"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIUserActivityRestoring"},"doc://com.microblink.ProductRecognition/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.microblink.ProductRecognition/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SH"},"doc://com.microblink.ProductRecognition/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.microblink.ProductRecognition\/s8SendableP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityConfiguration":{"role":"symbol","title":"ScanActivityConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanActivityConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes the object displayed while scanning."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanActivityConfiguration"}],"url":"\/documentation\/productrecognition\/scanactivityconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/showScanningAnimation(_:)":{"role":"symbol","title":"showScanningAnimation(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showScanningAnimation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts or stops the scanning animation."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/showScanningAnimation(_:)","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/showscanninganimation(_:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/showCustomMessage(_:completion:)":{"role":"symbol","title":"showCustomMessage(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showCustomMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Momentarily displays a message at the center of the view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/showCustomMessage(_:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/showcustommessage(_:completion:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/viewdidlayoutsubviews()"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/viewdidload()"},"doc://com.microblink.ProductRecognition/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s23CustomStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/imageView":{"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that displays the image being scanned."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/imageView","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/imageview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/scanningAnimationCompletion":{"role":"symbol","title":"scanningAnimationCompletion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningAnimationCompletion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"The block to execute after the scanning animation has stopped."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/scanningAnimationCompletion","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/scanninganimationcompletion"},"doc://com.microblink.ProductRecognition/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIStateRestoring"},"doc://com.microblink.ProductRecognition/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIContentContainer"},"doc://com.microblink.ProductRecognition/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIResponderStandardEditActions"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/resultText":{"role":"symbol","title":"resultText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The text displayed when there are results received."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/resultText","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/resulttext"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/showResultMessage(noResult:completion:)":{"role":"symbol","title":"showResultMessage(noResult:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showResultMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"noResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Displays the result message."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/showResultMessage(noResult:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/showresultmessage(noresult:completion:)"},"doc://com.microblink.ProductRecognition/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.microblink.ProductRecognition\/SQ"},"doc://com.microblink.ProductRecognition/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIAppearanceContainer"},"doc://com.microblink.ProductRecognition/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"},"doc://com.microblink.ProductRecognition/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSCoding"},"doc://com.microblink.ProductRecognition/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.microblink.ProductRecognition/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UITraitEnvironment"},"doc://com.microblink.ProductRecognition/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSObject"},"doc://com.microblink.ProductRecognition/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.microblink.ProductRecognition\/s28CustomDebugStringConvertibleP"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/noResultText":{"role":"symbol","title":"noResultText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noResultText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The text displayed when there are no results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/noResultText","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/noresulttext"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController":{"role":"symbol","title":"ScanActivityViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanActivityViewController"}],"abstract":[{"type":"text","text":"A view controller that you use to display the progress of a scan activity."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanActivityViewController"}],"url":"\/documentation\/productrecognition\/scanactivityviewcontroller"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/capturedImage":{"role":"symbol","title":"capturedImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The image captured by the camera."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/capturedImage","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/capturedimage"},"doc://com.microblink.ProductRecognition/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)UIFocusEnvironment"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/productrecognition\/scanactivityviewcontroller\/initwithcoder:"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanAgainButton":{"role":"symbol","title":"ScanAgainButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanAgainButton"}],"abstract":[{"type":"text","text":"A specialized button for placement on a result view controller."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanAgainButton"}],"url":"\/documentation\/productrecognition\/scanagainbutton"},"doc://com.microblink.ProductRecognition/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.microblink.ProductRecognition\/objc(pl)NSExtensionRequestHandling"},"doc://com.microblink.ProductRecognition/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.microblink.ProductRecognition\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ScanActivityViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ScanActivityViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ScanActivityViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/initWithCoder:","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/initWithNibName:bundle:","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/viewDidLayoutSubviews()","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.microblink.ProductRecognition\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Scanning Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainButton"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanActivityViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanActivityViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanActivityViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanActivityViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanActivityViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanActivityViewController\/title","value":"ScanActivityViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanActivityViewController\/fragments","value":[{"kind":"identifier","text":"ScanActivityViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanAgainButton\/title","value":"ScanAgainButton"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanAgainButton\/fragments","value":[{"kind":"identifier","text":"ScanAgainButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}