{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Sample","level":2,"type":"heading","text":"Sample"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The following example adds a viewfinder at the center of the screen:"},{"type":"text","text":" "},{"type":"image","identifier":"screenshot-subclass"}]},{"type":"codeListing","syntax":"swift","code":["import ProductRecognition","","class CustomViewController: SinglePhotoVC {","    ","    override func viewDidLoad() {","        super.viewDidLoad()","        ","        let image = UIImageView(image: UIImage(systemName: \"plus.viewfinder\",","                                               withConfiguration: UIImage.SymbolConfiguration(pointSize: 100)))","        self.view.addSubview(image)","        image.center = self.view.center","        ","        \/\/ The following sets the capture region to 80% of the screen area, centered.","        \/\/ The captured image in the capture region will then be displayed fullscreen in the result view.","        let width = self.view.bounds.width * 0.8","        let height = self.view.bounds.height * 0.8","        self.captureRegion = CGRect(x: (self.view.frame.width - width)\/2,","                                    y: (self.view.frame.height - height)\/2,","                                    width: width,","                                    height: height)","","        \/\/ This draws a border around the capture region","        let borderView = UIView(frame: self.captureRegion)","        borderView.layer.borderWidth = 5","        borderView.layer.borderColor = UIColor.darkGray.cgColor","","        \/\/ Insert the border behind the shutter button","        self.view.insertSubview(borderView,","                                belowSubview: self.shutterButton)","    }","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/subclasssinglephoto"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/subclasssinglephoto"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If you would like to overlay images or set the area to be captured, try subclassing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"},{"type":"text","text":"."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Subclassing SinglePhotoVC","role":"article","modules":[{"name":"ProductRecognition"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC"],["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC"]]},"seeAlsoSections":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults"],"generated":true}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomResults":{"role":"article","title":"Results View","abstract":[{"type":"text","text":"Customize result banners and cards."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customresults"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomSinglePhotoVC":{"role":"collectionGroup","title":"Customizing SinglePhotoVC","abstract":[{"type":"text","text":"Design the interface to better suit your app."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customsinglephotovc"},"screenshot-subclass":{"alt":"Custom Class","type":"image","identifier":"screenshot-subclass","variants":[{"url":"\/images\/screenshot-subclass.jpg","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"A view controller that manages the interface for capturing a single photo to be used for product detection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/productrecognition\/singlephotovc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/shutterButton":{"role":"symbol","title":"shutterButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"A button for capturing an image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/shutterbutton"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomCaptureView":{"role":"article","title":"Capture View","abstract":[{"type":"text","text":"Set a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion"},{"type":"text","text":" or replace the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton"},{"type":"text","text":" icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customcaptureview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/captureRegion":{"role":"symbol","title":"captureRegion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureRegion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The region of the camera preview to be captured."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/captureregion"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomScan":{"role":"article","title":"Scan View","abstract":[{"type":"text","text":"Modify the scanning activity indicator and the bottom bar for scanning again."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customscan"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}