{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCVPixelBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imgWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imgHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/imageutilsobjcpp\/createcvpixelbuffer(from:width:height:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/imageutilsobjcpp\/createcvpixelbuffer(from:width:height:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageUtilsObjCpp\/createCVPixelBuffer(from:width:height:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCVPixelBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":">"}],"title":"createCVPixelBuffer(from:width:height:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ImageUtilsObjCpp(cm)createCVPixelBufferFromData:width:height:","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"createCVPixelBufferFromData:width:height:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageUtilsObjCpp"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageUtilsObjCpp":{"role":"symbol","title":"ImageUtilsObjCpp","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageUtilsObjCpp"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageUtilsObjCpp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageUtilsObjCpp"}],"url":"\/documentation\/productrecognition\/imageutilsobjcpp"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageUtilsObjCpp/createCVPixelBuffer(from:width:height:)":{"role":"symbol","title":"createCVPixelBuffer(from:width:height:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCVPixelBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageUtilsObjCpp\/createCVPixelBuffer(from:width:height:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createCVPixelBufferFromData:width:height:"}],"url":"\/documentation\/productrecognition\/imageutilsobjcpp\/createcvpixelbuffer(from:width:height:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createCVPixelBufferFromData:width:height:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createCVPixelBufferFromData:width:height:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__CVBuffer","preciseIdentifier":"c:@S@__CVBuffer"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createCVPixelBufferFromData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"imageData"},{"kind":"text","text":" "},{"kind":"identifier","text":"width:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"imgWidth"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"imgHeight"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageUtilsObjCpp\/title","value":"ImageUtilsObjCpp"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageUtilsObjCpp\/fragments","value":[{"kind":"identifier","text":"ImageUtilsObjCpp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageUtilsObjCpp~1createCVPixelBuffer(from:width:height:)\/title","value":"createCVPixelBufferFromData:width:height:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageUtilsObjCpp~1createCVPixelBuffer(from:width:height:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createCVPixelBufferFromData:width:height:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}