{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFeaturesFor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation","text":"CVPixelBufferOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Features","preciseIdentifier":"c:objc(cs)Features","text":"Features"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/featuresextractorobjc\/getfeaturesfor(_:withrotation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/featuresextractorobjc\/getfeaturesfor(_:withrotation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorObjC\/getFeaturesFor(_:withRotation:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFeaturesFor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Features","preciseIdentifier":"c:objc(cs)Features"}],"title":"getFeaturesFor(_:withRotation:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)FeaturesExtractorObjC(im)getFeaturesForBuffer:withRotation:","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"getFeaturesForBuffer:withRotation:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorObjC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/FeaturesExtractorObjC":{"role":"symbol","title":"FeaturesExtractorObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturesExtractorObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeaturesExtractorObjC"}],"url":"\/documentation\/productrecognition\/featuresextractorobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Features":{"role":"symbol","title":"Features","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Features"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Features","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Features"}],"url":"\/documentation\/productrecognition\/features"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/FeaturesExtractorObjC/getFeaturesFor(_:withRotation:)":{"role":"symbol","title":"getFeaturesFor(_:withRotation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getFeaturesFor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withRotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Features","preciseIdentifier":"c:objc(cs)Features"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorObjC\/getFeaturesFor(_:withRotation:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getFeaturesForBuffer:withRotation:"}],"url":"\/documentation\/productrecognition\/featuresextractorobjc\/getfeaturesfor(_:withrotation:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CVPixelBufferOrientation":{"role":"symbol","title":"CVPixelBufferOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPixelBufferOrientation"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientation"}],"url":"\/documentation\/productrecognition\/cvpixelbufferorientation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getFeaturesForBuffer:withRotation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFeaturesForBuffer:withRotation:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Features","preciseIdentifier":"c:objc(cs)Features","text":"Features"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getFeaturesForBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__CVBuffer","preciseIdentifier":"c:@S@__CVBuffer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"withRotation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","preciseIdentifier":"c:@E@CVPixelBufferOrientation","text":"CVPixelBufferOrientation"},{"kind":"text","text":")"},{"kind":"internalParam","text":"rotation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1FeaturesExtractorObjC\/title","value":"FeaturesExtractorObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1FeaturesExtractorObjC\/fragments","value":[{"kind":"identifier","text":"FeaturesExtractorObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1Features\/title","value":"Features"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1Features\/fragments","value":[{"kind":"identifier","text":"Features"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1FeaturesExtractorObjC~1getFeaturesFor(_:withRotation:)\/title","value":"getFeaturesForBuffer:withRotation:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1FeaturesExtractorObjC~1getFeaturesFor(_:withRotation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getFeaturesForBuffer:withRotation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1CVPixelBufferOrientation\/title","value":"CVPixelBufferOrientation"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1CVPixelBufferOrientation\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}