{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Product Recognition SDK lets you build a fantastic in-store experience in your iOS app. The framework provides a camera interface through "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"},{"type":"text","text":" for product detection. You can also manually scan images and use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/StaticDiscoveryManager"},{"type":"text","text":" to get product data."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"logo-microblink"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"ProductRecognition","title":"ProductRecognition","symbolKind":"module","role":"collection","modules":[{"name":"ProductRecognition"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Setup","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Installation","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GettingStarted","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SDKManager"]},{"title":"Scanning Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainButton"]},{"title":"Camera View","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"]},{"title":"Manual Scanning","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/StaticDiscoveryManager"]},{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC"]},{"title":"Customization - Configurables","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicatorConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCellConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsConfiguration"]},{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"]},{"title":"Classes","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/AddProductsViewController","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/BGRImageCropper","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ContoursExtractor","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResult","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Feature","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Features","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractor","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorObjC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GradientBackgroundView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageUtilsObjCpp","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Item2dTrackingDataObjC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/LocationManager","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/NetworkBannerView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/NetworkManager","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProcessingData","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductsRepository","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainStoreView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/TrackedDataObjC"]},{"title":"Protocols","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ContoursExtractorDelegate","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorDelegate","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/StabilityDelegate"]},{"title":"Structures","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Products","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Promo","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultStoreCellConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SDKConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Store","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/StoreDetectionConfiguration","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/UserLocation"]},{"title":"Enumerations","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectorVersionObjC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC"]}],"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultIndicator":{"role":"symbol","title":"ResultIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicator"}],"abstract":[{"type":"text","text":"A view that indicates a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicator"}],"url":"\/documentation\/productrecognition\/resultindicator"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ContoursExtractorDelegate":{"role":"symbol","title":"ContoursExtractorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContoursExtractorDelegate"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ContoursExtractorDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContoursExtractorDelegate"}],"url":"\/documentation\/productrecognition\/contoursextractordelegate"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Item2dTrackingDataObjC":{"role":"symbol","title":"Item2dTrackingDataObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Item2dTrackingDataObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Item2dTrackingDataObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Item2dTrackingDataObjC"}],"url":"\/documentation\/productrecognition\/item2dtrackingdataobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsConfiguration":{"role":"symbol","title":"ResultDetailsConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a result details view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsConfiguration"}],"url":"\/documentation\/productrecognition\/resultdetailsconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/NetworkBannerView":{"role":"symbol","title":"NetworkBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkBannerView"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/NetworkBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkBannerView"}],"url":"\/documentation\/productrecognition\/networkbannerview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Feature":{"role":"symbol","title":"Feature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Feature"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Feature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Feature"}],"url":"\/documentation\/productrecognition\/feature"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityConfiguration":{"role":"symbol","title":"ScanActivityConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanActivityConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes the object displayed while scanning."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanActivityConfiguration"}],"url":"\/documentation\/productrecognition\/scanactivityconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanAgainConfiguration":{"role":"symbol","title":"ScanAgainConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanAgainConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes the scan again button and container."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanAgainConfiguration"}],"url":"\/documentation\/productrecognition\/scanagainconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SDKConfiguration":{"role":"symbol","title":"SDKConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKConfiguration"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SDKConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKConfiguration"}],"url":"\/documentation\/productrecognition\/sdkconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Installation":{"role":"article","title":"Installing ProductRecognition","abstract":[{"type":"text","text":"ProductRecognition can be installed via CocoaPods, Carthage, or Swift Package Manager. You can also manually add the framework to your project."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Installation","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/installation"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/GradientBackgroundView":{"role":"symbol","title":"GradientBackgroundView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientBackgroundView"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GradientBackgroundView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GradientBackgroundView"}],"url":"\/documentation\/productrecognition\/gradientbackgroundview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultStoreCellConfiguration":{"role":"symbol","title":"ResultStoreCellConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultStoreCellConfiguration"}],"abstract":[{"type":"text","text":"The configuration that describes a result store cell."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultStoreCellConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultStoreCellConfiguration"}],"url":"\/documentation\/productrecognition\/resultstorecellconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomScan":{"role":"article","title":"Scan View","abstract":[{"type":"text","text":"Modify the scanning activity indicator and the bottom bar for scanning again."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customscan"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/DetectionResult":{"role":"symbol","title":"DetectionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionResult"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectionResult"}],"url":"\/documentation\/productrecognition\/detectionresult"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Features":{"role":"symbol","title":"Features","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Features"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Features","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Features"}],"url":"\/documentation\/productrecognition\/features"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Promo":{"role":"symbol","title":"Promo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Promo"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Promo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Promo"}],"url":"\/documentation\/productrecognition\/promo"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerConfiguration":{"role":"symbol","title":"ResultBannerConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a promotion banner."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerConfiguration"}],"url":"\/documentation\/productrecognition\/resultbannerconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/NetworkManager":{"role":"symbol","title":"NetworkManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkManager"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/NetworkManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkManager"}],"url":"\/documentation\/productrecognition\/networkmanager"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultDetailsVC":{"role":"symbol","title":"ResultDetailsVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultDetailsVC"}],"abstract":[{"type":"text","text":"A view controller that displays the details of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultDetailsVC"}],"url":"\/documentation\/productrecognition\/resultdetailsvc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProcessingData":{"role":"symbol","title":"ProcessingData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingData"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProcessingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProcessingData"}],"url":"\/documentation\/productrecognition\/processingdata"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListConfiguration":{"role":"symbol","title":"ResultListConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a promotion list."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListConfiguration"}],"url":"\/documentation\/productrecognition\/resultlistconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultVC":{"role":"symbol","title":"ResultVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultVC"}],"abstract":[{"type":"text","text":"A view controller that displays the result of the scanned image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultVC"}],"url":"\/documentation\/productrecognition\/resultvc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/productrecognition\/resultbannerscrollview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/DetectorVersionObjC":{"role":"symbol","title":"DetectorVersionObjC","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectorVersionObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectorVersionObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectorVersionObjC"}],"url":"\/documentation\/productrecognition\/detectorversionobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductInfo":{"role":"symbol","title":"ProductInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductInfo"}],"abstract":[{"type":"text","text":"An object containing information of a product and available promotion."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductInfo"}],"url":"\/documentation\/productrecognition\/productinfo"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SDKManager":{"role":"symbol","title":"SDKManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKManager"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SDKManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKManager"}],"url":"\/documentation\/productrecognition\/sdkmanager"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCellConfiguration":{"role":"symbol","title":"ResultListCellConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCellConfiguration"}],"abstract":[{"type":"text","text":"The configuration that describes a result list row cell."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCellConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCellConfiguration"}],"url":"\/documentation\/productrecognition\/resultlistcellconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/AddProductsViewController":{"role":"symbol","title":"AddProductsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddProductsViewController"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/AddProductsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddProductsViewController"}],"url":"\/documentation\/productrecognition\/addproductsviewcontroller"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageProcessor":{"role":"symbol","title":"ImageProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageProcessor"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageProcessor"}],"url":"\/documentation\/productrecognition\/imageprocessor"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanAgainStoreView":{"role":"symbol","title":"ScanAgainStoreView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanAgainStoreView"}],"abstract":[{"type":"text","text":"A specialized label for the for placement in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC"}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainStoreView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanAgainStoreView"}],"url":"\/documentation\/productrecognition\/scanagainstoreview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductRecognitionVersionNumber":{"role":"symbol","title":"ProductRecognitionVersionNumber","fragments":[{"kind":"identifier","text":"ProductRecognitionVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for ProductRecognition."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductRecognitionVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/productrecognitionversionnumber"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanActivityViewController":{"role":"symbol","title":"ScanActivityViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanActivityViewController"}],"abstract":[{"type":"text","text":"A view controller that you use to display the progress of a scan activity."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanActivityViewController"}],"url":"\/documentation\/productrecognition\/scanactivityviewcontroller"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/EmbedderVersionObjC":{"role":"symbol","title":"EmbedderVersionObjC","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbedderVersionObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmbedderVersionObjC"}],"url":"\/documentation\/productrecognition\/embedderversionobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/DetectionResultObjC":{"role":"symbol","title":"DetectionResultObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionResultObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectionResultObjC"}],"url":"\/documentation\/productrecognition\/detectionresultobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/StaticDiscoveryManager":{"role":"symbol","title":"StaticDiscoveryManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StaticDiscoveryManager"}],"abstract":[{"type":"text","text":"Manually scan images and get their "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductInfo"}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/StaticDiscoveryManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StaticDiscoveryManager"}],"url":"\/documentation\/productrecognition\/staticdiscoverymanager"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/StoreDetectionConfiguration":{"role":"symbol","title":"StoreDetectionConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"StoreDetectionConfiguration"}],"abstract":[{"type":"text","text":"A configuration for the Store Detection feature"}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/StoreDetectionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StoreDetectionConfiguration"}],"url":"\/documentation\/productrecognition\/storedetectionconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"A view controller that manages the interface for capturing a single photo to be used for product detection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/productrecognition\/singlephotovc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductRecognitionVersionString":{"role":"symbol","title":"ProductRecognitionVersionString","fragments":[{"kind":"identifier","text":"ProductRecognitionVersionString"}],"abstract":[{"type":"text","text":"Project version string for ProductRecognition."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductRecognitionVersionString","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/productrecognitionversionstring"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultIndicatorConfiguration":{"role":"symbol","title":"ResultIndicatorConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultIndicatorConfiguration"}],"abstract":[{"type":"text","text":"A configuration that describes a promotion indicator."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicatorConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultIndicatorConfiguration"}],"url":"\/documentation\/productrecognition\/resultindicatorconfiguration"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Products":{"role":"symbol","title":"Products","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Products"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Products","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Products"}],"url":"\/documentation\/productrecognition\/products"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/shutterButton":{"role":"symbol","title":"shutterButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"A button for capturing an image."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/shutterbutton"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomCaptureView":{"role":"article","title":"Capture View","abstract":[{"type":"text","text":"Set a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion"},{"type":"text","text":" or replace the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/shutterButton"},{"type":"text","text":" icon."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customcaptureview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ContoursExtractor":{"role":"symbol","title":"ContoursExtractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContoursExtractor"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ContoursExtractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContoursExtractor"}],"url":"\/documentation\/productrecognition\/contoursextractor"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/StabilityDelegate":{"role":"symbol","title":"StabilityDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StabilityDelegate"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/StabilityDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StabilityDelegate"}],"url":"\/documentation\/productrecognition\/stabilitydelegate"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ScanAgainButton":{"role":"symbol","title":"ScanAgainButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanAgainButton"}],"abstract":[{"type":"text","text":"A specialized button for placement on a result view controller."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanAgainButton"}],"url":"\/documentation\/productrecognition\/scanagainbutton"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/FeaturesExtractorObjC":{"role":"symbol","title":"FeaturesExtractorObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturesExtractorObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeaturesExtractorObjC"}],"url":"\/documentation\/productrecognition\/featuresextractorobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/FeaturesExtractor":{"role":"symbol","title":"FeaturesExtractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturesExtractor"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeaturesExtractor"}],"url":"\/documentation\/productrecognition\/featuresextractor"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/Store":{"role":"symbol","title":"Store","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Store"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Store","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Store"}],"url":"\/documentation\/productrecognition\/store"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/BGRImageCropper":{"role":"symbol","title":"BGRImageCropper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BGRImageCropper"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/BGRImageCropper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BGRImageCropper"}],"url":"\/documentation\/productrecognition\/bgrimagecropper"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SubclassSinglePhoto":{"role":"article","title":"Subclassing SinglePhotoVC","abstract":[{"type":"text","text":"If you would like to overlay images or set the area to be captured, try subclassing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/subclasssinglephoto"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/LocationManager":{"role":"symbol","title":"LocationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationManager"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/LocationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocationManager"}],"url":"\/documentation\/productrecognition\/locationmanager"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CVPixelBufferOrientation":{"role":"symbol","title":"CVPixelBufferOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVPixelBufferOrientation"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CVPixelBufferOrientation"}],"url":"\/documentation\/productrecognition\/cvpixelbufferorientation"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomSinglePhotoVC":{"role":"collectionGroup","title":"Customizing SinglePhotoVC","abstract":[{"type":"text","text":"Design the interface to better suit your app."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customsinglephotovc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/productrecognition\/resultbanner"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/GettingStarted":{"role":"article","title":"Getting Started","abstract":[{"type":"text","text":"Add the necessary keys to get your project started."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/gettingstarted"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/TrackedDataObjC":{"role":"symbol","title":"TrackedDataObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackedDataObjC"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/TrackedDataObjC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TrackedDataObjC"}],"url":"\/documentation\/productrecognition\/trackeddataobjc"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/FeaturesExtractorDelegate":{"role":"symbol","title":"FeaturesExtractorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeaturesExtractorDelegate"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FeaturesExtractorDelegate"}],"url":"\/documentation\/productrecognition\/featuresextractordelegate"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ProductsRepository":{"role":"symbol","title":"ProductsRepository","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProductsRepository"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductsRepository","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProductsRepository"}],"url":"\/documentation\/productrecognition\/productsrepository"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/CustomResults":{"role":"article","title":"Results View","abstract":[{"type":"text","text":"Customize result banners and cards."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","kind":"article","type":"topic","url":"\/documentation\/productrecognition\/customresults"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ImageUtilsObjCpp":{"role":"symbol","title":"ImageUtilsObjCpp","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageUtilsObjCpp"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageUtilsObjCpp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageUtilsObjCpp"}],"url":"\/documentation\/productrecognition\/imageutilsobjcpp"},"logo-microblink":{"alt":"Microblink","type":"image","identifier":"logo-microblink","variants":[{"url":"\/images\/logo-microblink.png","traits":["1x","light"]}]},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListView":{"role":"symbol","title":"ResultListView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListView"}],"abstract":[{"type":"text","text":"A view that displays a list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListView"}],"url":"\/documentation\/productrecognition\/resultlistview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/UserLocation":{"role":"symbol","title":"UserLocation","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserLocation"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/UserLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserLocation"}],"url":"\/documentation\/productrecognition\/userlocation"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultListCell":{"role":"symbol","title":"ResultListCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultListCell"}],"abstract":[{"type":"text","text":"A table view cell that displays information on the list of results."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultListCell"}],"url":"\/documentation\/productrecognition\/resultlistcell"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/captureRegion":{"role":"symbol","title":"captureRegion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureRegion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The region of the camera preview to be captured."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/captureRegion","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/singlephotovc\/captureregion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Setup","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Installation","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GettingStarted"]},{"title":"Scanning Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanActivityViewController","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainButton"]},{"title":"Camera View","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"]},{"title":"Result Views","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultIndicator","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultListCell","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultDetailsVC"]},{"title":"Customization - Samples","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomSinglePhotoVC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomCaptureView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomScan","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CustomResults","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SubclassSinglePhoto"]},{"title":"Classes","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/AddProductsViewController","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/BGRImageCropper","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectionResultObjC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Feature","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Features","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/FeaturesExtractorObjC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/GradientBackgroundView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageProcessor","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ImageUtilsObjCpp","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/Item2dTrackingDataObjC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/LocationManager","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/NetworkBannerView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProcessingData","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ScanAgainStoreView","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/TrackedDataObjC"]},{"title":"Variables","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductRecognitionVersionNumber","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ProductRecognitionVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/CVPixelBufferOrientation","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/DetectorVersionObjC","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/EmbedderVersionObjC"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/title","value":"ResultIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultIndicator\/fragments","value":[{"kind":"identifier","text":"ResultIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1Item2dTrackingDataObjC\/title","value":"Item2dTrackingDataObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1Item2dTrackingDataObjC\/fragments","value":[{"kind":"identifier","text":"Item2dTrackingDataObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1NetworkBannerView\/title","value":"NetworkBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1NetworkBannerView\/fragments","value":[{"kind":"identifier","text":"NetworkBannerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1Feature\/title","value":"Feature"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1Feature\/fragments","value":[{"kind":"identifier","text":"Feature"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1GradientBackgroundView\/title","value":"GradientBackgroundView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1GradientBackgroundView\/fragments","value":[{"kind":"identifier","text":"GradientBackgroundView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1Features\/title","value":"Features"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1Features\/fragments","value":[{"kind":"identifier","text":"Features"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/title","value":"ResultDetailsVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultDetailsVC\/fragments","value":[{"kind":"identifier","text":"ResultDetailsVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ProcessingData\/title","value":"ProcessingData"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ProcessingData\/fragments","value":[{"kind":"identifier","text":"ProcessingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/title","value":"ResultVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultVC\/fragments","value":[{"kind":"identifier","text":"ResultVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectorVersionObjC\/title","value":"DetectorVersionObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectorVersionObjC\/fragments","value":[{"kind":"identifier","text":"DetectorVersionObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1AddProductsViewController\/title","value":"AddProductsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1AddProductsViewController\/fragments","value":[{"kind":"identifier","text":"AddProductsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor\/title","value":"ImageProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageProcessor\/fragments","value":[{"kind":"identifier","text":"ImageProcessor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanAgainStoreView\/title","value":"ScanAgainStoreView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanAgainStoreView\/fragments","value":[{"kind":"identifier","text":"ScanAgainStoreView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanActivityViewController\/title","value":"ScanActivityViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanActivityViewController\/fragments","value":[{"kind":"identifier","text":"ScanActivityViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC\/title","value":"EmbedderVersionObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1EmbedderVersionObjC\/fragments","value":[{"kind":"identifier","text":"EmbedderVersionObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectionResultObjC\/title","value":"DetectionResultObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1DetectionResultObjC\/fragments","value":[{"kind":"identifier","text":"DetectionResultObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanAgainButton\/title","value":"ScanAgainButton"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ScanAgainButton\/fragments","value":[{"kind":"identifier","text":"ScanAgainButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1FeaturesExtractorObjC\/title","value":"FeaturesExtractorObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1FeaturesExtractorObjC\/fragments","value":[{"kind":"identifier","text":"FeaturesExtractorObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1BGRImageCropper\/title","value":"BGRImageCropper"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1BGRImageCropper\/fragments","value":[{"kind":"identifier","text":"BGRImageCropper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1LocationManager\/title","value":"LocationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1LocationManager\/fragments","value":[{"kind":"identifier","text":"LocationManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1CVPixelBufferOrientation\/title","value":"CVPixelBufferOrientation"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1CVPixelBufferOrientation\/fragments","value":[{"kind":"identifier","text":"CVPixelBufferOrientation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1TrackedDataObjC\/title","value":"TrackedDataObjC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1TrackedDataObjC\/fragments","value":[{"kind":"identifier","text":"TrackedDataObjC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageUtilsObjCpp\/title","value":"ImageUtilsObjCpp"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ImageUtilsObjCpp\/fragments","value":[{"kind":"identifier","text":"ImageUtilsObjCpp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/title","value":"ResultListView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListView\/fragments","value":[{"kind":"identifier","text":"ResultListView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/title","value":"ResultListCell"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultListCell\/fragments","value":[{"kind":"identifier","text":"ResultListCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}