{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishProcessingPhoto"},{"kind":"text","text":" "},{"kind":"internalParam","text":"photo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhoto","preciseIdentifier":"c:objc(cs)AVCapturePhoto"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/singlephotovc\/photooutput(_:didfinishprocessingphoto:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/singlephotovc\/photooutput(_:didfinishprocessingphoto:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/photoOutput(_:didFinishProcessingPhoto:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AVCapturePhotoCaptureDelegate.photoOutput(_:didFinishProcessingPhoto:error:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishProcessingPhoto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhoto","preciseIdentifier":"c:objc(cs)AVCapturePhoto"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"photoOutput(_:didFinishProcessingPhoto:error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ProductRecognition@objc(cs)SinglePhotoVC(im)captureOutput:didFinishProcessingPhoto:error:","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"captureOutput:didFinishProcessingPhoto:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC/photoOutput(_:didFinishProcessingPhoto:error:)":{"role":"symbol","title":"photoOutput(_:didFinishProcessingPhoto:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishProcessingPhoto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhoto","preciseIdentifier":"c:objc(cs)AVCapturePhoto"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC\/photoOutput(_:didFinishProcessingPhoto:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureOutput:didFinishProcessingPhoto:error:"}],"url":"\/documentation\/productrecognition\/singlephotovc\/photooutput(_:didfinishprocessingphoto:error:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/SinglePhotoVC":{"role":"symbol","title":"SinglePhotoVC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SinglePhotoVC"}],"abstract":[{"type":"text","text":"A view controller that manages the interface for capturing a single photo to be used for product detection."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/SinglePhotoVC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SinglePhotoVC"}],"url":"\/documentation\/productrecognition\/singlephotovc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"captureOutput:didFinishProcessingPhoto:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:didFinishProcessingPhoto:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"captureOutput:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"output"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishProcessingPhoto:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCapturePhoto","preciseIdentifier":"c:objc(cs)AVCapturePhoto"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"photo"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC~1photoOutput(_:didFinishProcessingPhoto:error:)\/title","value":"captureOutput:didFinishProcessingPhoto:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC~1photoOutput(_:didFinishProcessingPhoto:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:didFinishProcessingPhoto:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/title","value":"SinglePhotoVC"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1SinglePhotoVC\/fragments","value":[{"kind":"identifier","text":"SinglePhotoVC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}