{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPageControl","preciseIdentifier":"c:objc(cs)UIPageControl"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/resultbannerscrollview\/pagecontrol"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView\/pageControl","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The control that displays a horizontal series of dots, each of which corresponds to a result banner in the view."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPageControl","preciseIdentifier":"c:objc(cs)UIPageControl"}],"title":"pageControl","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:18ProductRecognition22ResultBannerScrollViewC11pageControlSo06UIPageH0Cvp","modules":[{"name":"ProductRecognition"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView/pageControl":{"role":"symbol","title":"pageControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPageControl","preciseIdentifier":"c:objc(cs)UIPageControl"}],"abstract":[{"type":"text","text":"The control that displays a horizontal series of dots, each of which corresponds to a result banner in the view."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView\/pageControl","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition\/resultbannerscrollview\/pagecontrol"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/productrecognition\/resultbannerscrollview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/productrecognition\/resultbanner"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}