{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/productrecognition\/resultbannerscrollview\/scrollviewdidenddecelerating(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/productrecognition\/resultbannerscrollview\/scrollviewdidenddecelerating(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView\/scrollViewDidEndDecelerating(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIScrollViewDelegate.scrollViewDidEndDecelerating(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"title":"scrollViewDidEndDecelerating(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ProductRecognition@objc(cs)ResultBannerScrollView(im)scrollViewDidEndDecelerating:","modules":[{"name":"ProductRecognition"}],"navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}]},"hierarchy":{"paths":[["doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView"]]},"references":{"doc://com.microblink.ProductRecognition/documentation/ProductRecognition":{"role":"collection","title":"ProductRecognition","abstract":[{"type":"text","text":"Effortlessly scan products in the grocery store and get all needed data about them."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition","kind":"symbol","type":"topic","url":"\/documentation\/productrecognition"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView":{"role":"symbol","title":"ResultBannerScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBannerScrollView"}],"abstract":[{"type":"text","text":"A scrollable view that displays multiple "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBannerScrollView"}],"url":"\/documentation\/productrecognition\/resultbannerscrollview"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBannerScrollView/scrollViewDidEndDecelerating(_:)":{"role":"symbol","title":"scrollViewDidEndDecelerating(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBannerScrollView\/scrollViewDidEndDecelerating(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"url":"\/documentation\/productrecognition\/resultbannerscrollview\/scrollviewdidenddecelerating(_:)"},"doc://com.microblink.ProductRecognition/documentation/ProductRecognition/ResultBanner":{"role":"symbol","title":"ResultBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultBanner"}],"abstract":[{"type":"text","text":"A view that displays the preview of a result."}],"identifier":"doc:\/\/com.microblink.ProductRecognition\/documentation\/ProductRecognition\/ResultBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultBanner"}],"url":"\/documentation\/productrecognition\/resultbanner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scrollViewDidEndDecelerating:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/title","value":"ResultBannerScrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView\/fragments","value":[{"kind":"identifier","text":"ResultBannerScrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView~1scrollViewDidEndDecelerating(_:)\/title","value":"scrollViewDidEndDecelerating:"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBannerScrollView~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/title","value":"ResultBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.microblink.ProductRecognition~1documentation~1ProductRecognition~1ResultBanner\/fragments","value":[{"kind":"identifier","text":"ResultBanner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}